### ISSUE TITLE
Altary Way name issue

### ISSUE THREAD

**Issue by terrapin47** [Treeofsavior/EnglishTranslation#1125]
제단로   Altary Way

This is an area east of Fedimian that has a lot of Altars, and quests related to them.  Is it really "Altary Way", or should it be "Altar Way"?  The original Korean text also appears to translate to "Altar" or "to Altar".

**Comment by Sunaries** [comment]
What about "Way to the Altar" :yum:

**Comment by terrapin47** [comment]
There are many altars there though.

**Comment by imcgames** [comment]
Altar Way or Altary Way would do. Which is better?

**Comment by terrapin47** [comment]
My vote goes for Altar Way.

**Comment by slowmelodic** [comment]
Road of Altar maybe o.o

**Comment by BloodHeartless** [comment]
My vote is for "Altar way"

**Comment by ensata** [comment]
There's actually more to this map name than merely being a place full of shrines and related quests. You can find some lore in Fedimia that says that the five maps leading up to the city are thematically linked to the 5 deadly sins – and no, that's not a typo – five sins. Pilgrims need to go through all of them before arriving at the Cathedral.

The maps are: 
- Starving Demon's Way
- Pilgrim Path
- Altary Way
- Forest of Prayer
- Apsimesti Crossroad

The first map was originally translated as "Starving Demon's Road" before I renamed it. I renamed many of the others (not just these) but I never submitted them.

At the time, I came up with "Way of Altars" for this one. 

I also had "Way of Pilgrims" or "Way of Pilgrimage", and "Way of Prayers", but that's obviously not a complete translation. The last one is tougher since it's Lithuanian, (it literally means "to pretend"), but I had "Way of Masks".

**Comment by zhouyu47** [comment]
Yes, and several of the pilgrims along the path talk about it as well.
