### ISSUE TITLE
What are different between ETC_20150312 (removed) & ETC_20150317 (current)? And others something.

### ISSUE THREAD

**Issue by wazho** [Treeofsavior/EnglishTranslation#115]
Hello! This is Salmon.

Excuse me. Why uploaded two version ETC_20150312 (removed) & ETC_20150317 (current). What are different between them? I have a project that wanna make all players of my county can join the translation work, so I have to understand all of .TSV file what they means.

Thanks much :)

---

I merge both of 'Korean' (xxx.tsv) and 'English in progress' (xxx_en.tsv). All users can see two languages, then system _grep (detect the same words)_ automatically [reference terms](https://github.com/Treeofsavior/EnglishTranslation/wiki/2.%20Reference) in text can be referenced for users in a message.

And this project isn't only for people that have translating skill. Everyone can vote the others translated text they agree. I think this is very important for _EACH PLAYERS_ can help this game grow up, not only part of players.

Why we need the crowd voting? Just like [this post](https://github.com/Treeofsavior/EnglishTranslation/issues/50). Different countries, languages or folkways could make the words to express means different. So we need a good and smart way to solve it, right? :)

[My project is over here.](https://github.com/grass0916/Tree-of-Savior-Chinese-Translation-Voting)

Regards, Salmon

**Comment by imcgames** [comment]
The previous ETC.tsv contained just a part of the text since it was for a test run whereas the new ETC.tsv file is a full version of the file that will be used in the actual game test. (but of course, as the game is still in development, there will be more text lines to be added later on). Also, you may have noticed that the string codes changed in the new ETC.tsv. :)
