### ISSUE TITLE
Revelator vs Oracle/Prophet

### ISSUE THREAD

**Issue by aentan** [Treeofsavior/EnglishTranslation#120]
계시자로 is more like oracle or prophet. Revelator just sounds weird. Would be good to know the context.

**Comment by Nagoda** [comment]
This issue was brought up in the Word/Phrase translation thread here, https://github.com/Treeofsavior/EnglishTranslation/issues/50

Ultimately we didn't come to a strong conclusion and felt we needed more context. I personally think Prophet sounds the best, whether or not it's most accurate. If you have additional thoughts to add, feel free.
