### ISSUE TITLE
Machine translations

### ISSUE THREAD

**Issue by Nagoda** [Treeofsavior/EnglishTranslation#124]
So the files have recently been updated with more lines, and in them there are thousands of lines of what is obviously machine translated dialog.

Looking at the new Quest files, a huge amount of these new lines are impossible to correct just by fixing the grammar or rewriting.  With the bad ones, the intent of the sentence is totally incomprehensible, and even with most of the better ones it's not possible to fix without some guesswork. Some examples:

-I was burned secretly as go toilet. {Nl} Thank you very much.
-Speaking the only so, it was too burger. {Nl} However, Nante you helped me, I was really good.
-I would have thought to while watching the Ironbaum. {Nl} their friends really awesome friend.
-As before, I do I become many people who go back and forth this way. {Nl} people I'm really interesting.
-It is really embarrassing that came out to run away alone. {Nl}

I understand that our current goal here is just to get something rough and functional together for an English test client, and I suppose these are better than nothing for testers, but I think it's going to make the actual translation job harder. 

People could previously just look for blank lines in the EN files to know which lines need to be done. Now that we have thousands of lines of word-shrapnel, each line needs to be carefully read and then determined to be unusable before it gets translated, which is significantly more work for the people who can actually do the translations.

I'm curious what others think, it seemed worth discussing. I'm not sure what should be done. Maybe we need pull requests with nothing but deletions of bad lines in them, or some other way to help sort out the lines that are beyond salvaging.

**Comment by ericxinui** [comment]
Totally agree, today I was reading some of the translated ones, and it's more work to be done when the lines translated are like that. I think those who are translating at least should read and try to make sense into the lines before pulling it :)

**Comment by MarkofKain** [comment]
Yeah, I also thought it was a mistake to automatically add machine translations. I think it slows down the progress of people that can actually translate those complex sentences.

**Comment by Sunaries** [comment]
It's a lot of text and dialogue. I don't think everything can be properly translated because it's huge, there is little context and the amount of contributors makes a difference.  

I assume this project does help IMCgames to get the International Test Server up and running faster than scheduled with somewhat comprehensible dialogue. The company will still need to hire professionals into their localization team to review the lines and make revisions.

**Comment by imcgames** [comment]
Thank you for sharing your thoughts. :+1: 
We are trying out different ways to speed up the English translation process so the full game texts and machine translations were added in hopes that it would be of help to those translating the texts. 
However, since it isn't quite functioning as it was intended, we have updated our files with the blank lines again like before :smile:
