### ISSUE TITLE
OTC and Git Branch Questions

### ISSUE THREAD

**Issue by HeArchitect** [Treeofsavior/EnglishTranslation#1265]
Hi, I'm a software developer and new to ToS. I have some questions about the translation workflow:
1. The Open Text Client (OTC), which is a game client software. Will we use this to test the translations? If yes, where could I possibly get it? If not, the translation work is modifying the file context on the Github files, is this correct?
2. The Github branch. I saw only the English Translation branch under the repo. If we are going to make a Chinese Translation branch, where shall we put the load? A new branch under the English Ver, A new branch under the Treeofsavior or A new repo clone from the English Ver under a private repo?

Hoping to get answers back soon and we are ready to start the work.
Thanks
-Peng

**Comment by Sunaries** [comment]
Greetings,
1. The OTC can be used to test the translations, yes. In this Issue https://github.com/Treeofsavior/EnglishTranslation/issues/705 it is explained on how to enable RTT (Realtime Translation Tool) while being in the game. It is not necessary to use this if you want to contribute, but it is handy because you will know the context of the specific dialogue/line. 
2. There are several other language repositories: https://github.com/search?utf8=%E2%9C%93&q=tree+of+savior - But as of now only the English version is officially supported and managed by IMC.

**Comment by HeArchitect** [comment]
Okay, Thanks, Great Help.

**Comment by HeArchitect** [comment]
@Sunaries How could I get the OTC client on my pc and running? Is this mean that I have to be a contribute on the English version? Because I can't find the OTC link on the website/forum.

Thanks

**Comment by Sunaries** [comment]
@xia50 Please read this developer note for more information about the OTC: http://blog.treeofsavior.com/en/?p=284
