### ISSUE TITLE
Status Point or Attribute Point?

### ISSUE THREAD

**Issue by Sunaries** [Treeofsavior/EnglishTranslation#196]
I have been adapting to "Attribute Point", because I think it sounds good. But it is officially Status Point (스테이터스 포인트).
What is your verdict on this matter?

**Comment by imcgames** [comment]
Actually, both are used in game.
We use Attribute for 속성 and Status for 스테이터스 :)

**Comment by Sunaries** [comment]
Since 'attribute' is a broad term used in Tree of Savior (skills, attacks, elemental statuses etc), I'll suggest the following: 스테이터스 -> 능력치 (Ability Point)

**Comment by Nagoda** [comment]
"Status Point" is a bit strange sounding. Is this another Konglish term?

It seems like "Status Point" is derived from the commonly used English "Stat Point" or "Stats", to describe stuff like Strength, Agility, Intelligence, etc., but the problem is that "Stat" is actually short for "Statistic". In English games, "Status" is much more frequently used to describe buffs or debuffs ("Status Effects")

 Sunaries suggestion of "Ability Point" sounds good to the ear. My only concern is It might be a little easy for players to confuse "Ability" and "Attribute", since they look similar and have very similar meanings. I might suggest another translation for  속성 to avoid this, maybe "Element", or "Property" if it needs to be more general.

**Comment by MarkofKain** [comment]
I think Attribute Points generally refers to character stats such as STR, DEX, CONS, STA, INT and Ability Points (or Skill Point) would refer to points you get to level up the spells/passives of your character. Status Point sounds like something you would get to increase your chances of inflicting (or resisting) a status ailment such as blind, confusion, poison, slow, etc.

I would have to vote for Attribute Points if we're solely talking about STR, INT, SPR, DEX.

**Comment by Sunaries** [comment]
I believe the term 'attribute' is used in different aspects of this game. Status Point in this game refers to points that can be distributed into STR, DEX, INT, SPR and CON. 
@Nagoda Yes, you can call it a Konglish term. 

> An attribute describes to what extent a character possesses a natural, in-born characteristic common to all characters in the game. Attributes are also called statistics, characteristics or abilities. - http://en.wikipedia.org/wiki/Statistic_(role-playing_games)

That's Wikipedia which everyone can edit, but in the end the terms: 'attribute', 'status', 'stat', 'ability' all share a similar meaning in the modern games we have of today and it's all used differently in each one of them. 

There is a game who calls their skills an ability, the other one calls it an

**Comment by Nagoda** [comment]
The word "status" doesn't appear a single time in the Wiki article you linked. "Attribute", "stat", "ability" at all relatively interchangeable. "Status" is not among them.

**Comment by kontownik** [comment]
Imo should be something like Status point -> Stat point; stats;   same as @Nagoda  mentioned coz status is for ex. frozen, petrified etc. like it was in RO1 right?

**Comment by ttgmichael** [comment]
Should we close this?

**Comment by Sunaries** [comment]
> Should we close this?

IMC has confirmed to continue with Status.
