### ISSUE TITLE
로우 [weapon] should be Crude [weapon].

### ISSUE THREAD

**Issue by dlam** [Treeofsavior/EnglishTranslation#237]
I'm currently proofreading some of the existing translations in ITEM_en.tsv.

From my understanding, 로우 -> Low.

The existing translations are inconsistent between "Low", "Crude", and "Mediocre", and has potential for awkwardness within context. i.e., Using a recipe to craft a "Low Falchion" and receiving a "Mediocre Falchion" as a result.

I should also mention that "Low [weapon]" is awkward in English, because "low" generally refers to an amount, which is typically inferred from context or explicitly stated. Much better would be "Low-grade" or "Crude" - i.e., 로우 폴쳔 -> Low-grade Falchion or alternatively, 로우 폴쳔 -> Crude Falchion.

@imcgames what is the intended translation for 로우 in the context of weapons / equipment?

Some examples of existing translations:
- 로우 폴쳔 -> Mediocre Falchion
- 로우 카스카라 -> Mediocre Kaskara
- 로우 라이트 크로스보우 -> Crude Light Crossbow
- 제작서-로우 바스타드 소드 -> Recipe-low Bastard Sword

**Comment by Sunaries** [comment]
I believe this discussion is ongoing here: https://github.com/Treeofsavior/EnglishTranslation/issues/56

**Comment by dlam** [comment]
@Sunaries Thanks, keeping this issue open so that it is hopefully addressed by a dev.

**Comment by imcgames** [comment]
Equipment names, including the one mentioned above, have been changed when the issue was brought up previously so those names are actually no longer used in game. 
We may be doing a revamp of the translation files some time in the future to wipe out those lines that have been changed. 
For now, you may skip that part regarding equipments  :)
