### ISSUE TITLE
How Item Requirements/Rewards are Shown

### ISSUE THREAD

**Issue by MarkofKain** [Treeofsavior/EnglishTranslation#283]
So if you watch the video https://www.youtube.com/watch?v=6SH7nv1SZjs&index=1&list=PLZmwVtJXg551uyb5Rlsd9qdVtwkiMpaiw#t=11m46s you'll see items you receive or need are shown as "(item name)(number amount)(ea or ea obtained)"  EX: "Hanaming3 ea"

I would like to change lines 3311 and 4661 in ETC_en.tsv from "ea obtained" and " ea " " to " x#" or maybe even " x# received", where # is the amount of items. So in the previous example       "Hanaming3 ea" becomes "Hanaming x3". But I wasn't sure how to write it in the line since the item amounts aren't in there; and I also want to know what you guys think before doing anything.

**Comment by hasenbanck** [comment]
I have a strong feeling that it's something like this:
Printf("%d@ID3311", amount)

(If you know Printf in C/C++)

So I think that you can't change the order in this case, since there is no placeholder for the amount as of right now.

But I can be wrong! I personally think that this hard coded ordering should be generally avoided and that placeholders should always put into the translation string. But that something that only the developer can tell us more about and can fix in the end.

**Comment by Sunaries** [comment]
I think it should remain at "obtained". "Received" is when you are given something while "obtained" means you put effort into it, so you earned it. 

I've had trouble with this while I've been editing ETC.en.tsv. However, you came up with an idea to make it better, but I have also an idea. Instead of an 'x', we can use parenthesis to indicate an amount. 
1. Hanaming Petal x3 
   **Hanaming Petal**
   x3 obtained 
2. Hanaming Petal (3)
   **Hanaming Petal**
   (3) obtained 

Ideally, it would be better to put "obtained" in front of the item name. 

_obtained Hanaming Petal x3_
_obtained Hanaming Petal (3)_

But I don't know how it is programmed nor do I have knowledge on programming languages.

**Comment by TOSBase** [comment]
Well they already have something like this implemented but it seem like they are not using is consequently enough.

e.g. ETC_20150317_001651 {Year} {Month} {Day} {Hour} hr {Min} min {Sec} sec

That's how lines with dynamic values should look like so we could use

ETC_20150317_003311 obtained {Item} x{Count}
or
ETC_20150317_003311 obtained {Item} ({Count})

This will greatly help in the future especially with more languages supported so it would be a good idea if the devs can change this line in the korean version so we can use it like this.

**Comment by Sunaries** [comment]
@TOSBase Except it is already written perfect in Korean. They won't change the particular line in the Korean version. For programming questions, you'd have to ask @imcgames.

**Comment by TOSBase** [comment]
Well @imcgames is reading this as far as I know so i suggested that they change the korean version to use the {Item} and {Count} variables because this is required so that we can use it aswell, even though the korean version is already written perfect.

**Comment by imcgames** [comment]
Thank you for your suggestions. This has actually been discussed internally for a while and we are in progress of changing it to use variables. :)
