### ISSUE TITLE
Differences between the official reference wiki entries and the merged translations

### ISSUE THREAD

**Issue by hasenbanck** [Treeofsavior/EnglishTranslation#299]
I have progressed with my translation tool now so much, that I can search for standard terms in the TSV files and locate inconsistent usage of those. Right now, I get my reference data from the official wiki entries. But those entries stand in contrast with the merged translations. I think we need to find a way to fix those entries in the reference wiki ASAP, or find anther way, to create a stable reference data pool (Items, Monster, NPC names etc.).

http://pastebin.com/409fVfJk

Explanation:
Source text = Korean original
Target text = English translation
Standard term = Name as found in the reference wiki
TSV-entry = Name as found in the English translations

Some log entries don't have a TSV-entry. In that case the word was used in a longer context and you have to search for it inside the original TSV files.

How can we resolve these inconsistencies?

**Comment by Sunaries** [comment]
The official wiki contains inconsistencies. For example: 
- 무고사 (Mugosa) = Wugushi. But in the wiki it is referred as 우구시. 
- 독수리깃 is Eagle Feather and not Eagle Git.
- "Two-Hand Sword" should be "Two-Handed Sword", etc.
-  "Recipe-Cane" should be "Recipe - Cane", etc.

The _TSV-entries_ contains higher quality translations , but some of the _standard terms_ are good. 
The wiki should be updated to resolve some of your issues. However, the wiki only provides a limited amount of info compared to the files. Most of the correctly translated text and descriptions are in the _TSV-entries_. 

Only @imcgames can edit the wiki, but nobody else can. I think it would be wise if they allow members to edit the wiki, so that the terms and names can be updated to a better quality and the appropriate translation. All they need to do is give feedback on it and check if its alright or not.

**Comment by hasenbanck** [comment]
My goal is to unify all standard terms in the TSV files. Right now we have no way to track those standard terms, since the ones in the wiki is are wrong on many occasions and the entries in the TSV files are not finished yet. I could fix the entries from the wiki myself in my own code repository (using the TSV -entries), but I think it would be better to fix the wiki entries. 

It's also near to impossible to know "which" entries are finished. QA is kinda impossible right now.

**Comment by imcgames** [comment]
UI for items can sometimes be limited and that is why we try to keep some item names as short as we can. 

As for the wiki edits, it is limited to prevent possible trolling activities so for the time being, we will apply the changes in wiki when suggestions are made. But we do plan to make the edits public in the future when the game is released so please hang on until then :smile:

**Comment by hasenbanck** [comment]
Yes, but you are also merging the changes with the longer names with the pull requestes people are doing. So you're not consistent in your work.

Right now the wiki is a bad place to start for reference names, since the actual translations are different (which you seem to aprove).

In the short term, I will extract the standard terms from the ITEM and ETC files manualy and will try to track them by scanning each merge for new entries.
