### ISSUE TITLE
Suggestions/Feedbacks #2

### ISSUE THREAD

**Issue by imcgames** [Treeofsavior/EnglishTranslation#308]
First of all, thank you and a big shout out to the contributors. We really appreciate your efforts :+1: 
If you have any feedback and/or suggestions, we'd be glad to hear them so let us know through the comments below or you can create new issues if it calls for a new discussion :smiley:

**Comment by ceddc** [comment]
Hello,

I've found an inconsistency (find :  "Helga" in all files) :  what is the correct name between all these?
- ETC_20150317_000400   Helgasercle
- ETC_20150317_000553   Avatar of Helgasecle
- ETC_20150317_005147   Helga Cercle
- ETC_20150317_005780   Rage of Helgacercle
- ETC_20150428_011248   Defeat Helga Sercle that is occupying the Maze Tower!
- ITEM_20150317_002047  Helgacercle Card

**Comment by Sunaries** [comment]
@ceddc Helgacercle / Helgasercle

**Comment by TOSBase** [comment]
Helga is a first name in Germany and apparently also "used mainly in Scandinavia, Iceland, Germany and Hungary".
Meaning: Meaning    heilagr - "holy", "blessed"
Source: http://en.wikipedia.org/wiki/Helga
So it could be first name + last name Helga Cercle / Helga Sercle / ....

**Comment by imcgames** [comment]
Helgasercle  :smile:

**Comment by Mephilin** [comment]
I'm sorry for asking it here, but I'd like to know if IMC is planning to support ToS translation to other languages the same way as for English. It would be cool to have some official announcement about that since I see a lot of translation activity recently. I'm struggling to know if this work is going to be useful in some way, or all those people including me are just wasting their time. I'd like to start translation from English to Russian, but does IMC need that?

**Comment by Clebertos** [comment]
Hellow IMC, is it possible to add _pt-br Files? (Portuguese - Brazil)
We made a translate group to our language and we have already 70% of the files in our language, just waiting for it.
Thank you.

**Comment by Sunaries** [comment]
@Clebertos They only accept English for now. Since it is the primary language set for the international server. Besides, there are more files than you see on Github, but it's not available here yet.

**Comment by ttgmichael** [comment]
shall we close this issue?
