### ISSUE TITLE
Google Spreadsheet

### ISSUE THREAD

**Issue by imcgames** [Treeofsavior/EnglishTranslation#348]
To make the translation process more convenient and accessible, we've also opened a Google Spreadsheet for translations to test it out  [**here**](https://docs.google.com/spreadsheets/d/1kbbkUbkRttqY_lH542vt5l9L7IO9W9s3GwS4YA0xRmg/edit?usp=sharing).

Please let us know what you think about it. Do you like it? Is it easier to use? Should we consider switching to Google Spreadsheet? Any other comments and feedbacks are also welcome! :smile:

**Comment by ceddc** [comment]
Seems it will be hard to keep track of change and to merge the modifications.
I like the idea of tosbase with user translation with people to check and commit here ! https://github.com/Treeofsavior/EnglishTranslation/issues/347

**Comment by hasenbanck** [comment]
I don't think that accessibility is right now the real problem. The most important things right now are the consistency of the translations and the QA.

But tracking all changes in a google spreadsheet would be great for QA. But that would also be a lot of work...

**Comment by Gardosen** [comment]
Please stay away from Google Spreadsheets for this kind of work.

As a Project Lead for Quality Assurance in a Gaming Company I can tell you the following:
Spreadsheets are inefficient, brings a low performance as bigger they become and should not be used for this kind of work. if you want to offer a collaborated translation system to a wide community, you have to work with administrative controlling tools, like we are doing it on our web translation tool. people can suggest translations to each element, and we will then select in a specific period the best suggestions, based on the rating of the users to each element. after this we will hand them over to your company via pushing it to this github.

My Team partner Flash already finished the first rough version of our web translation tool which we will develop in the next days more and more, to make it more handy for people.
i know that you would create a dependency to us if you agree with working with us together and let us manage the translation via the web translation tool.

but we have years of experience with those stuff, because of our work on the translation pack for Ragnarok Online 2 Legend of the Second (we translated the whole Korean client to English and German) please let us help you, in that case, to build a proper community-based system which is easy and handy for the people.

Kind regards
Gardosen from TOSBase.com

**Comment by hasenbanck** [comment]
Yeah, spreadsheets are always kinda pain in the ass, but right now we have no tool at all. And i don't think that IMC has understood the necessity as of right now to include a tool to help the QA process. I wouldn't employ a system purely based on ratings. We need a tool which let us keep the tracks of every line, might even use the history that git provides us and knows of a role concept. We have some very good translators as of right now. They should be the safeguard for now letting in wrong translations, machine translated gibberish and non consistent work.

Also: Standard terms (like the ones in the reference wiki) is still a big problem. We need to find a way to track their use and control their life-cycle.

**Comment by Gardosen** [comment]
@hasenbanck : imcGames is totally aware of the necessity of the QA process, that's why they implemented the OTC system. many good translations where based on google + logical connection to the game while playing it. don't underestimate the skill level of players who are fully into a game. also, because of the great OTC System, the community will be the QA at the end.
this system is an experiment, but i see a great potential in it. especially because i know the loca QA from companies. they are never as good as gamers who are playing a game 6 hours a day.
bugs in the logical meaning of words, are going to be found by players within minutes. a full QA Team will not see it.

also the user rating i mentioned is just an example. the tool is just a prototype where we are currently collecting as much feedback as possible from the users, that we can provide a proper easy tool on the release date to the community.
as already mentioned you can check informations to this tool here https://github.com/Treeofsavior/EnglishTranslation/issues/347 

Kind regards
Gardosen

**Comment by hasenbanck** [comment]
If you track the commit history, you will see that machine translated lines are often heavily re-edited by the translators. UI and simple stuff can be translated with logical connection and reference videos / screenshots, but translating the quest texts and item description is a whole other issue.

QA can't be archived by simply using git and having an open community. QA can only be archived if we focus our efforts in checking the translations done by IMC and machine translators by experiences translators. But those translators need guidance. Normally you have an QA workflow to keep sure that your translations are well and consistent. Right now our workflow here is as following: People edit stuff -> IMC merge them.

So we don't keep track of the changes at all and don't really know which lines are done and which lines need more work. For that we need a controlling or a better workflow.

It also hurts a lot that we use a special file format, that is not compatible with standard CAT tools. We have so many standard terms right now, that are used in many different files, I would murder for a translation memory program. 

Your tool is a step in the right direction, since we really need to merge the view of source and target language and need to merge all files into one abstracted view (Most people don't use Search&Replace when they change stuff and keep forgetting to change those translated terms in other places...).

**Comment by Gardosen** [comment]
i agree with you aber the machine translated stuff, but I think we should also keep in mind, imcGames were honest and said "we are not able to provide a proper native translation for this, and will need your help) so maybe exactly this will be the small flame who will make this translation as same successful as the one from minecraft or other games where the community supported the translation.

beside this: the files of the client are in tsv it's not a common ending, but the file structure themselves is a standard file. it can be opened with any tool like notepad, notepad++, excel (after setting up the separator to be a tab) e.g
that's why we also thought in the first run about a real tool for this. shown here https://github.com/Treeofsavior/EnglishTranslation/issues/232#issuecomment-102508920

I see you are really into this too, probably you would like to join me and flash for a private discussion to get to know the opinion of each other better. we are always open for suggestions and opinions to improve stuff.

Kind regards
Gardosen

**Comment by emailboxu** [comment]
Personally don't like Google Spreadsheets for this kind of work, I think Git is better for current translations. If the OTC is released I'm pretty sure both are going to be redundant anyway.

**Comment by TOSBase** [comment]
@hasenbanck I'm currently working on a history view for the translation tool that might help.

![tool_history](https://cloud.githubusercontent.com/assets/11730284/7730692/f2aae026-ff1b-11e4-85e9-895a6cc629a5.png)

**Comment by Sunaries** [comment]
I have personally never used Google Spreadsheet and I am now familiar with Github. One thing that frustrates me currently on Github is that I am unable to edit ginormously files. Whenever I edit in ITEM or ETC, it takes a while for the letters to appear. This doesn't happen to blank files, because I have contributed to the JOBSTEP file which went smoothly. The latter file has been removed from Github.

I do like the history feature and that you can leave notes on the edits done by other contributors. For now, I'll stick with quick and small edits until the OTC releases.

**Comment by imcgames** [comment]
Thank you for your suggestions.
We considered google spreadsheet for its edit features and the fact that you can see the edits, suggestions, and comments of other people right away directly in each line without having to check each pull request as done in Github. This also has the advantage of preventing contributors to work on the same lines or outdated lines. 
But of course, there are pros and cons to all means and we wanted to test and see what would be our best option so feel free to let us know your feedback.
