### ISSUE TITLE
Font Strawpoll

### ISSUE THREAD

**Issue by emailboxu** [Treeofsavior/EnglishTranslation#400]
Thought I'd make a StrawPoll for the font thing, here it is:

http://strawpoll.me/4639597

**Comment by megaoka** [comment]
Has someone made a list of what all the fonts look like? I can't seem to find examples.

**Comment by emailboxu** [comment]
There's one on the main page of the GitHub, but here's an imgur mirror:

http://i.imgur.com/hYDoPz5.jpg

**Comment by megaoka** [comment]
Huh, I didn't think that 2002 would be the more popular option.

**Comment by Sunaries** [comment]
@imcgames Could you test the following fonts ingame and take a screenshot: 
- Raavi
- PF Din Text Cond Pro
- JejuGothic
- Noto Sans

Out of all the possible options from the Strawpoll, I choose for Gautami.

**Comment by laurencee** [comment]
I dont think this is a true/fair example of what the fonts would actually look like in game.

Looking at some of the images it appears as if there are compression artifacts, probably due to using jpeg which you should never use when comparing text.

This comparison should have been based on a png or some other lossless image format.

Look at these easy to notice examples of jpeg artifacting: http://stackoverflow.com/a/7752936/2631967

**Comment by emailboxu** [comment]
The poll's slowed down considerably and is resting around 950 votes, currently 2002 is leading by a good 76 votes ahead of Quattrocento.

**Comment by dwolfx** [comment]
Helvetica sounds good to me...

## 

Att,
Victor Hugo Nogueira
Cel: (11) 9-5156-5851
Skype: viictorhu

2015-06-18 22:05 GMT-03:00 emailboxu notifications@github.com:
