### ISSUE TITLE
Change of translation file names

### ISSUE THREAD

**Issue by imcgames** [Treeofsavior/EnglishTranslation#419]
Hi guys! 

We will be updating the translation files and change its file names on July 1. 
Currently, the English files have '_en' at the end of the file names but we plan to change it so that the Korean files will have indicators (maybe '_kor'), not the English files. Also, some files will have its name changed as well.
We feel that this would be necessary to make better use of github with game client such as directly using the files in github when playing the game. 

Unfortunately, we haven't found a way to get github to retain file history after the name change so the file's history may not be kept after the update. 
If you do know a way to keep file history even after the name changes, let us know and we'll be open to trying it out. 

As you may know, we have renewed our website and opened our forums and we thank you for the warm responses you've shown us. 
We hope to bring you some good news in the near future and until then, please send us your continued support for Tree of Savior. 
(And of course, the translations too :wink: )

**Comment by megaoka** [comment]
Hi IMC!

The history of a file whose name has been changed can be followed using "git log --follow"
For example if we change the name of ETC_en.tsv to ETC.tsv (and the original ETC.tsv to ETC_kor.tsv) we can run the following in the [master] branch:

`git log --follow ETC.tsv`

This will show all changes, plus the ones made before the file name change. 

If you want to preserve the file history on github.com, you could try creating a branch with the old file names/structure before changing the files on the `master`, that way revision history could still be viewed without using the command line.

**Comment by imcgames** [comment]
Hi @megaoka 

Thanks for the suggestions! I think the problem with git follow is that it doesn't seem to make it through the Github web interface for Github users to view easily. 
(for average users/translators, git may need quite some 'getting used to' unless you're familiar with the likes of it)
I guess we may try to go with your other suggestion of creating backup branch with old file names :wink:

**Comment by megaoka** [comment]
:+1:

**Comment by Herestt** [comment]
Hi,

Github does a simple `git log` command to create the history of a file. 

The problem with `git mv <file_name> <new_file_name>` is that you only change the name of the file for the HEAD revision. If you checkout another commit before the renaming, your file will have its previous name. This is the reason why `git log <file_name>` cannot find the history of a file before it was renamed. To keep the history after renaming a file you'll have to work on the whole branch, or maybe tree (depends on if you built your `master` branch with a `merge` or `rebase` strategy). 

Apparently your tree is made by merging pulled requests. So I think that after a renaming everybody will have to work on a new fork. Otherwise your repository will be messed up at a next pulling request - due to the fact that the forked repositories won't have the name of their changed files.

The `git filter-branch --tree-filter '<command>' HEAD` command is the only solution I know that can deal with a whole tree - where the `<command>` makes a `git mv` if the targeted file is part of the commit. Afterwards a simple `git log <file_name>` will show you the full history of your file.
Here is a shell script that does the job on your working directory: https://gist.github.com/emiller/6769886

If you are on Windows you'll have to make your own batch.

**Comment by imcgames** [comment]
Hi @Herestt !
We tried the shell script you informed us and seems like it's just what we needed!
Thank you very much! :+1:
