### ISSUE TITLE
The meaning of a particular term

### ISSUE THREAD

**Issue by Sunaries** [Treeofsavior/EnglishTranslation#432]
While evaluating a pull request of a user, I've come across the term **Divine Day**. 
This is referred from 신수의 날 in Korean. The official site refers this important event as ["The Day of Divine Tree"](https://treeofsavior.com/intro/). 

Maybe @imcgames can elaborate on this? What is the actual meaning of 신수의 날? Divine Day _or_ The Day of Divine Tree? (or should it be The Day of the Divine Tree)?

**Comment by emailboxu** [comment]
https://treeofsavior.com/intro/

I believe it's "The Day of the Divine Tree". "Divine Tree" is a proper noun that appeared in the world and destroyed stuff.

**Comment by emailboxu** [comment]
Errrrrrrrrrrrrrrrm. In that link they refer to it as "The Day of Divine Tree", so maybe it is that? I feel like "The Day of the Divine Tree" makes more sense tbh, but it's their game so..

**Comment by imcgames** [comment]
Yup, @emailboxu is correct. It's the day when the Divine Tree suddenly soared.
'The Day of Divine Tree' in the official site should replace Divine Day. 
(we decided it to be The Day of Divine Tree not so long ago so some other versions of it may exist in the translation files :laughing: we'll be cleaning that up at once later on)

As to The Day of Divine Tree or The Day of the Divine Tree, we chose the former because it is mentioned a lot in the game so we thought we'd go with the shorter one. But if you feel that it is awkward to the point that it must be changed, let us know and we are open to changing it if necessary. :wink:

**Comment by Nagoda** [comment]
"The Day of Divine Tree" does sound awkward I think. "The Day of the Divine Tree" is more natural , but both versions are definitely a mouthful for a term that's used a lot in the game.

"Divine Day" is a little more cryptic but it sounds much better to my ear, and obviously is a lot shorter.

**Comment by Chaosbelow** [comment]
It certainly is a mouthful to say "The Day of the Divine Tree" and even "The Day of Divine Tree" is a lot too. It is mentioned quite a lot in game and is only more troublesome in the middle of sentences. For example: "My parent passed away on the Divine Day because of them." (Line 1659) of Quest.tsv. If I change this to "My parent passed away on The Day of the Divine Tree because of them" it becomes even more of a mouthful. I think Divine Day is a good abbreviation of "The Day of the Divine Tree." How about earlier in the games text/story it is shortened to "The Divine Day"? That way later on in the story using "The Divine Day" would be shorter and cleaner, still retain its meaning. Or if IMC can come up with a better abbreviation or better phrasing for that particular day.

**Comment by ensata** [comment]
I took the angle of looking at "Divine Tree", before you would go and name a day after it. There's a lot of names and synonyms for it, since I'm pretty sure it's a reference to the world tree, which is common in a lot of myths. Yggdrasil is the name for it in Norse myth, which you've probably heard of.

I took a quick look at Latvian myth and thought about calling it the "Day of Austras", or the "Day of Saules", or some such. 

You can also be boring and consider "Heavenly Day", since that one's just a synonym.

**Comment by imcgames** [comment]
Day of Austras was actually considered but we thought it might not sound too familiar for players.
But do you think 'Day of Austra's would be better than 'Day of Divine Tree'?

**Comment by Chaosbelow** [comment]
I think so, having a symbol or a memorable name such as "Austra" sounds a lot nicer than Divine Tree. Relating the event to a simple name such as Austra is a lot cleaner then Divine Tree. Divine Tree sounds a bit more ambiguous. Not to mention it sounds a little broken without adding a "the" infront of "Divine Tree." It's almost like instead of saying "Happy Day Jesus Was Born" instead of saying "Merry Christmas!" It also has to explain a little too much every time it is said instead of just relating the day to a symbolic/memorable word. I'd say go with Day of Austras.

**Comment by ensata** [comment]
I don't think Baltic myth, as a whole, is familiar to players. In fact, you're probably introducing it to many new people, with this game. As long as you use the name Austras Koks correctly, I think players will like it.

In fact, I was trying to figure out how many mythical references you actually made, aside from Austras and the Goddesses. I'm still not sure if the Vubbe is a reference of the Baubas, for example... but I don't know what the Vubbe look like.

**Comment by imcgames** [comment]
So with your suggestions, we discussed about giving the 'Day of Divine Tree' a different name.
Instead of using English, we decided to use foreign language instead and 'Medis Diena' was our pick. 
(For 'Day of Austras', after checking, we found that Austras means Austrian in Lithuanian so we decided it wouldn't be right to use it)

If it isn't so bad that we need to change it again, we'll begin replacing the existing term in the near future.  :wink:

**Comment by ensata** [comment]
Oh, I didn't catch that. Austras is the goddess of light only in Latvian myth, but I shouldn't have mixed all the Baltic myths together in the first place. Some JRPGs screw around with names, so I'm used to seeing mash-ups.

Anyway, I think 'Medis Diena' is side-stepping the reason behind my approach: What's the tree's name? Does it have one, or did the citizens give it a name? How do they refer to the tree itself? In fact, to make it sound more natural, I might actually refer to the event as 'The Day that xxx Appeared'.

Alternatively, we can go back to Korean and try to re-translate it from scratch. 의 날 means 'Day of', or 'xxx Day', depending on preference. 신수, as far as I can figure out, means 'Divine', in the sense of one's divine right, luck, fortune, or blessing. I could be wrong, though.

My understanding of the lore is that the tree is a disaster, and not a blessing. If I were to localize it, and not translate, I would call it the 'Day of Reckoning'.

**Comment by imcgames** [comment]
신수 means 'Divine Tree' which is the reason why 신수의 날 was previously called 'The Day of Divine Tree'.

For 신수, 'Divine Tree' seems better than giving it a new name because it is easy and direct so we'd like to keep it that way. But for the event/day itself, we decided give a name to the event itself separately because it has that much importance in the game world.

Also, we decided to stray from English because if we had to give it a new name, we didn't want it to be  'Day of XXX', 
(If there was an awesome word that could contain the whole idea of 'The Day of Divine Tree' in one word, we could have considered it but there wasn't any that satisfied us :sob: )
Therefore, we chose 'Medis Diena' because it is Lithuanian and also contains the meaning of what we want the 신수의 날 to have. 

So that's how 'Medis Diena' was decided and hope this explains things a bit better :smiley:

**Comment by ensata** [comment]
That's strange. I've checked my dictionaries more closely, but I simply can't translate it to 'Divine Tree'. 신 means 'God', but 수 doesn't mean Tree at all, based on what I have on me. I have it as 'Divine Hand', 'Divine Imprisonment', or 'Divine Water'... which is the opposite of tree.

Putting that aside, I'm still not sure about the name, since 'Medis Diena' still simply means 'Day of the Tree'. Divine tree sounds a bit generic, and the tree - not the day - should have a nickname to summarize how the players and the world's citizens feel about it. Calling it 'Day of xxx' would then be the second step, and the name allows you to have many more dialogue options when it's only the tree you're talking about.

This is roughly how my thought process went: The name 'Divine Tree' sounds awkward because in English, calling something 'divine' usually means that it belongs to the gods, or the gods are directly responsible for it - except that the goddesses are missing, so why would you call it divine?. I doubt the world's citizens would call the day 'divine', because the day was a disaster, not a blessing. From there, if I try to translate "The day where a disaster of a heavenly scale occurred", I thought of the "Day of Reckoning", which is a Christian term for a horrible disaster that's marked by the gods. It might still not be the best, but now it makes the day sound much more important.

Of course, we can also just give up and stick to Day of Divine Tree, even though it doesn't convey a lot of meaning. For a side hobby, I've spent too much time thinking about this.

**Comment by Sunaries** [comment]
@ensata IMC is right. Korean is a very contextual language and a word can have multiple meanings. 신수 in hanja (神樹) can mean 'Divine Tree'.

**Comment by ensata** [comment]
Oh, I wasn't disagreeing. I was just pointing out the oddity that I couldn't find it in my sources for some reason, even though I found other meanings of 수. I probably just did something wrong... but it doesn't mean we can't exploit the multiple meanings, so I listed those, anyway. I'm just trying to throw out alternate translation methods.

**Comment by ensata** [comment]
Celestial! That's what I was looking for. Celestial Tree.

The Day of the Celestial Tree.

I also got "Day of Celestial Arbor" out of a brainstorm, but I don't know how other people feel about the word Arbor.

**Comment by Chaosbelow** [comment]
Honestly 'Medis Diena' sounds good and I think we should keep it like that. Even when you say " on the Day of Medis Diena" it sounds good too. Sounds a lot less ambiguous and more significant in a way that relates to the Day of the Divine Tree. I also like how kinda cryptic it is, sounds good. :+1:

**Comment by ensata** [comment]
Except I said that 'Medis Diena' is dodging part of the issue. It's not about making it sound good or cool (although that's a plus,) it's about making it fully accurate, yet still sound like natural English. 

It's also plain wrong. Medis Diena simply means "Day of the Tree" in the Lithuanian language, and it only sounds interesting because it's another language. In fact, you've already made a mistake by saying "Day-of-Day-of-Tree". You're also no longer calling it divine - you're literally calling it Arbor Day.

The Korean writers decided to call it 신수의 날, which literally translates to "Day of Divine Tree" - and that's fine. I like the meaning - but literally translating it is the first step: the second step is editing it to natural English prose, and enhance it - in English. Going for Medis Diena is cheating.

So, I broke it down and tried make 'Divine Tree' sound accurate and natural, and I've used up all the tricks I can think of, based on what little information I have.

Is the 'Divine Tree' a reference to the World Tree, Austras Koks? But no, that's the Latvian name.
Invent an original English term based on the event's description? Day of Reckoning. No.
Create a lore-friendly nickname for the tree? Denied.
Cheat with hanja double meanings? Nope.
English has a lot of synonyms, so break it down further? Celestial Tree.

I probably should have done that one first. In English, "Divine" strongly implies that God did it. Celestial doesn't.

**Comment by ttgmichael** [comment]
I'm tied between the original term and Celestial Tree because I think there isn't enough context (from the source) for me to picture the event.

@imcgames, the synopsis on the website states that the tree "suddenly emerged". But here you state that it's the day when the tree "soared". So did the tree suddenly appear out of nowhere (not sure why it would be divine or celestial because it caused so much havoc), or was it that the tree (originally planted there by the Goddesses or something) just suddenly grew out of control? I'm guessing that the Plant Cataclysm starts with this tree growing out of control. So if the latter, then we need to edit the synopsis to something like "Day of the Divine Tree Awakening" because that way it sounds likes its the day when the tree grew and when people realized something was definitely wrong with their world. Celestial would only be more befitting if the tree has no connection with the Goddesses or some divine being.

**Comment by Xenobius2501** [comment]
Sorry to barge in like that, but if this still hasn't been finalized I'd like to point out that "Medis Diena" is yet again, wrong if you consider Lithuanian grammar. Yes, possessive case strikes again. Now, I can come up with two alternatives.

1) Go with grammatically correct, but rather plain "Day of the Tree" - "Medzio Diena"

2) Try to incorporate the "divine" into the word and turn it into "Sventmedzio diena". There's some word play involved here, so I'll explain. In Lithuanian, specifically when you start examining the morphology, the prefix "svent" (Švent) is derived from the word "Šventas" - sacred, holy, saint. For example, "Šventvagystė" means sacrilege, Šventykla means "temple" and so on. 

At the same time, Šventmedis is a Lithuanian word for a real-life plant, namely - Cleronedrum, or glorybower which has a rather curious etymology (ok, I had to google this part, but still) - it  comes from Greek "kleros" which means "chance" or "destiny" and dendron, "tree".

**Comment by ensata** [comment]
"Sventmedzio - The Tree of Destiny". Now that, I can get behind. I think we've also got a potential new name for "Tree of Savior", here. People were always questioning the odd game name.

Okay, this is seriously getting on my nerves now, for another reason. I thought IMC had some Lithuanian consultants? Translating it into English is one thing, since almost every Korean game is badly translated, but what in the world is going on?

**Comment by Xenobius2501** [comment]
Just a general tip for future reference - compared to English, Lithuanian is very, how should I put this -  particular about cases. That, and it has a ton of them. Nouns have seven cases, each having fourteen suffixes (seven singular, seven plural) that vary depending on the word stem.   Since we're at trees and such at the moment I'll use the word tree (medis) as an example. To keep it simple (_cough_), only singulars:

Nominative: Medis
Genitive: Medzio
Dative: Medziui
Objective/Accusative: Medi
Instrumental: Medziu (not be confused with Medzių - that's a plural genitive because "u" as grown a tail here)
Locative: Medyje
Vocative: Medi (yeah, voc. is often the same as some other cases... But not always).

**Comment by ensata** [comment]
Oh, right. Still.
_Sventmedis: The Tree of Destiny ~_ The sword may only have two sides, but the roots grow ever deeper.

Or something like that. I'm not writing the game. Not even getting paid.

That said, if you want to find some alternative words, then "divine" was not the fully correct translation. At it's very most literal, the Korean is calling it the "God Tree" — but keep in mind that there are many ways to interpret why it's "Godlike".

I tried using Celestial, which is apparently "dangaus" in Lithuanian... and there's other stuff.

**Comment by ttgmichael** [comment]
I support Sventmedzio Diena too xD. It keeps the "divine" meaning from the Korean scripts ^^.

**Comment by ensata** [comment]
Okay, I probably should have caught this sooner, but _kleros_ doesn't mean chance or destiny... the Latin "cleros" means "clergy", while the Greek "kleros" means a certain type of plot of land. The Greek word for destiny is _Moira_. No idea what your source is.

I guess that means "The Tree of Destiny" isn't valid in this instance - it would've been pretty cool, too, with Laima and everything.

**Comment by Xenobius2501** [comment]
http://dictionary.reference.com/browse/clerodendrum here, for example - here the chance / lot translation is provided, but since I don't really know Greek, I can only rely on what Google sends my way. 

It's also unlikely anyone will dig deep enough to start analyzing the botanical name of the plant - Lithuanian name is Šventmedis, and common translation to English is glorybower, with clerodendrum being a "proper" botanical term.

**Comment by ensata** [comment]
Well, you're the one who looked at the botanical name, not me. The Divine Tree's supposed to be filled with meaning, and it's up to the writer if they want to add layers of symbolism over it. Not many will dig for it, but it's a bonus for the dedicated fans.

http://www.biblestudytools.com/lexicons/greek/nas/kleros.html says that the 'chance' meaning isn't about destiny, but about the more mundane drawing of 'lots', similar to flipping a coin.

**Comment by Xenobius2501** [comment]
Anyhow.
Ever since I saw that "Medis Diena" abomination mentioned in game by NPCs it became apparent that we should change it. 
As it is, it makes no sense whatsoever, since leaving it in nominative case makes it sound like "Tree. Day." with full stop/period between unrelated words.

I'd say Šventmedžio Diena is the best compromise we have for now. Botany aside, it's commonplace in Lithuanian language to form words like this. 

Examples include:  
Savaitgalis - formed from Savaitė [week] + Galas [end]) - weekend;
Penktadienis - from Penktas/Penkta [fith] and Diena [day] - Friday. 
Naujienlaiškis - from Naujiena [news] + Laiškas [letter] - Newsletter 
...and so on.

Therefore, a word like Šventmedis formed from Šventas [sacred/divine] + Medis [tree] is probably the best I can come up with to keep it "Lithuanian" and preserve the "Day of the Sacred Tree" meaning.

**Comment by imcgames** [comment]
Actually, Sventmedis was considered but there were opinions that it sounded too complex so that's why we settled for just Medis. 
(medis diena was already foreign enough so we didn't want to add complex sounds on top of it)
Medzio Diena doesn't have that complexity of pronounciation in play so I'll bring that up to the devs.
Let me know if you have other suggestions though, that doesn't sound too complex, and I'll try to bring that up as well.

**Comment by Xenobius2501** [comment]
Well, since they originally intended to name that event "Day of the Tree" Medžio Diena (which means exactly that) is probably the next best choice if Šventmedžio Diena was deemed too complex. While somewhat plain, it still conveys the meaning and is not a broken piece of machine translation that "Medis Diena" was. 

I'm not really sure alternatives will be any better - "Day of the Sacred Tree" for example, would turn it into three words instead of two - "Švento Medžio Diena" - as would adding any other adjective, for that matter.
