### ISSUE TITLE
"..." or ".. "

### ISSUE THREAD

**Issue by Sourpusss** [Treeofsavior/EnglishTranslation#483]
We need to decide what's going on with ellipses for ToS.  Before people started translating, ellipses were written as ".. " (two periods and a space), but now it seems like people are using correct ellipses.  Technically, ellipses shouldn't be used this way in speech, but this is another issue.  This being the case, it's actually arbitrary how they look when being used this way.  However, for the sake of consistency, we need to decide if we're going to correct them all to the classic english "..." or retain them as ".. "  

If we're going to "correct" them all, so be it, and lets start knocking those out.  Otherwise, please retain them as ".. " and stop adding a third period.

**Comment by Chaosbelow** [comment]
I made a topic about this already: 
#437 

Didn't get a lot of response. I for one think we should stick with the two ellipses, seems fine enough to me. No one is really gonna nitpick that there is two periods instead of three. Plus two periods just keeps it very slightly cleaner.

**Comment by Sourpusss** [comment]
Ah, my bad.  I brought it up due to there being quite a bit of pull requests dealing with it within the past few days.  There's currently one waiting now, so I felt like we should get this squared away.  I'm all for retaining the ".. " ellipses, as, like you said, it seems fine / looks cleaner.  The request dealing with it before was asked to revert them, so until we get some input I guess we should keep the status quo.

**Comment by megaoka** [comment]
@ensata said he had a reason for the the unicode format "…" 

My vote is for either or. As long as they're all uniform. It really doesn't matter. @imcgames decide on something!

**Comment by Nagoda** [comment]
It's not really our job here to invent new standards for English punctuation. Using two dot ellipses reads more as a strange translation oversight or a typo than anything else, and standardizing all the game text to have three dots needs to happen sooner or later. I respectfully disagree that nobody will notice.

**Comment by imcgames** [comment]
Alright, let's settle for three dots to comply with standards for English punctuation :smile:

**Comment by ensata** [comment]
Actually, it's totally okay to use ellipses in speech in several different ways. Its use in creative writing is different than in an article, and it's also literally the second sentence on Wikipedia. 

Either way, whatever you think, two dots is not standard punctuation. It'll be recognised as a typo, but you won't know if it's meant to be one dot, or three. That should've been enough reason, already.

As for using the Unicode ellipsis character, this relates to a rendering bug that can occur in printed books and user interfaces — if you write the ellipsis by typing three periods, there is a chance that word wrap will cut the ellipsis in half, so you get one dot on one line, and two on the other. The Unicode character counts as a single character, so that will never happen. In fact, MS Office and LibreOffice's autocorrect silently replaces it for you. Printed books aren't relevant here, but the problem can also occur in Korean and Japanese games that haven't been reprogrammed for the way that English is laid out, or certain rendering methods in general.

I actually don't care if you prefer to type three dots, though. Just don't do two dots.
