### ISSUE TITLE
Individual word/phrase translations

### ISSUE THREAD

**Issue by Nagoda** [Treeofsavior/EnglishTranslation#50]
I don't speak Korean so my ability to help is limited, but I notice when something sounds goofy in English. I've come across a couple words that are used a lot in the Quest file as translated so far which seem like they might not be quite right.

The first word that appears a lot is "Devil", which seems to be a major enemy type that appears many many times in the Quest dialog, and players will no doubt be fighting them a bunch. I believe the original Korean word used is "마족". The most common usage of "Devil" in English is to refer directly to Satan ("the" Devil). When it's used to refer to lesser evil spirits, it often has a kind of mischievous or impish sort of connotation. It's simply not used very often in games media to describe evil or unholy monsters.

I mentioned this in one of my pull requests and another user suggested "Demon" as a better choice. I lack the context needed to know if Demon is a more accurate translation, but it certainly seems to sound better.

The second odd word is "Revelator". The Quest file makes many mentions of "Revelations", "Revelators", and seems to refer to the player character directly as being "the Revelator", as some kind of "chosen one" title. The original Korean word seems to be "계시" or "계시자". My main problem with Revelator is that it's a very seldom used and obscure word, to the point where it ends up just sounding like a too literal translation.

I wonder if "Prophet" might be a more useful title that has more or less the same meaning as Revelator. It would be helpful if someone could provide better context for what the original script is trying to say.

**Comment by AEJung** [comment]
That's riiight, it is referring to the player character. There was some quest dialog from the first G-Star (2013) video that talks about how your character had been visited by "the Goddess" (Laima) in their dreams and told to journey to Klaipeda (probably among other things). As for an actual title for it...Revelator...Prophet... When you really delve into the origins and meanings of the words they both work well, but I think when most people thinking of a prophet is someone who is predicting the future based on what God told them (or, actually, gods -- I think more of Greek mythology when I hear "prophet" instead of Christian)? Whereas a revelation tended to be more of a task or mission that God wanted them to complete. So Revelator is probably just a tiny bit more appropriate based on popular knowledge. 

Ah and yeah, demon is probably more appropriate. 마족 is Chinese-derived Korean, 마 (ma) meaning evil, 족 (jok) meaning tribe. I mention the Chinese part because it can be hard to find correct definitions for them in Korean dictionaries. 

Hope that helped!

**Comment by MarkofKain** [comment]
This is an interesting debate about what the player is and how they interact with the goddesses. Prophets and revelators seem more popular in Abrahamic religions, whereas oracles and seers are from antiquity such as ancient Greece.

The only way to figure out the best word is to know how the character interacts with the Goddesses and what they tell him. Does he see visions? Do the Goddesses speak directly to him (either physically or through dreams). Or is he simply manipulated to go here and do this.

Which then brings us to the question, what knowledge is imparted unto him. The title Revelator would imply that the Goddesses have told him some truth about the world and then proceeds to spread the word of God. A Prophet would be shown snippets of the future that have yet to happen, pieces of a puzzle that he must fit together to form a story.

But if what AEJung says is true then hes not really told anything except to visit a place. In this case I don't think either term fits who he is. You could say "Prophecies" instead of "Revelations" depending on the context. Unless somebody else can think of a more appropriate name it seems like the best one would be to refer to him as "The Prophesied One" or as Nagoda said "The Chosen One".

**Comment by vegax87** [comment]
Let me guess, the Revelator is the true Savior referenced in the game title.
Usually a Revelator means  a chosen one who reveals spiritual or religious teachings exactly like a Prophet.

but take a look at this statement:
QUEST_LV_0100_20150312_001222   We pray that the blessings of the Goddess will always be with the Revelator who saved us

A guy who SAVED us. (maybe is the player but I don't know the context)

this ISN'T a Revelator but a Savior who saves people.
If you take an english dictionary it says:

Savior
 1.
a person who saves, rescues, or delivers:
the savior of the country.

**Comment by AEJung** [comment]
Ah, I should have said that the word they're using (계시) specifically refers to revelation, with 계시자 simply meaning "revelation man/person". The word for prophecy is 예언. 

From the bits and pieces of the story they've released until now (I haven't had time to read through all the quest dialog yet... ) it seems like the revelations they received were like a 'Hey, us goddesses are in trouble can you come help us?' Which would mean your character is not only a savior to the people, but also to the goddesses. And then in turn a savior of the world. <:

**Comment by Sunaries** [comment]
Hello,

I just discovered this topic and I am new to GitHub. Very hard to use. +_+;
I've come across 마족 in ETC, but this can mean different things. There is also little context, so it's hard. For now I've translated it as Demon.

**Comment by SedorikuA** [comment]
Hi,

I found out about the OTC for TOS on Mmosite and yeah like Sunaries, I am new to GitHub. I don't speak Korean but I'll do what I can to help and eliminate words and sentences that doesn't make sense or typo errors.

**Comment by Nagoda** [comment]
It sounds like there's some consensus about translating "마족" as "Demon", at least based on what we know at the moment. 

If there are no major objections, I'll perform a find>replace for "Devil">"Demon" on the quest file the next time I do a pull request, and we can try to keep consistent on future instances of it.

It seems like Revelator is much less clear, but the discussion is certainly interesting. Maybe it makes sense to stick with Revelator for now, until we have a more complete picture of the story.

If people have found other word or phrase translations that they'd like to get opinions on, definitely feel free to add them to the discussion here.

**Comment by Sunaries** [comment]
I am skimming through some lines and I spot "큐바스" multiple times. Other users have coined this term as "Kubus". The spelling I see from my perspective is Qubas/Cubas. What do you think?

**Comment by imcgames** [comment]
Great discussion topic guys! :+1: 
For now, we're going with 'Demon' for 마족 and 'Revelator' for 계시자.
But if you feel it's a really bad choice :worried:  , let us know and we'll be very open to considering changes. :smile:

**Comment by AEJung** [comment]
Spadow - It's hard with the names of monsters unless we can find the inspiration for them. >: If IMC could decide for themselves a romanized spelling for their Konglish it would be really helpful I think, haha. Especially because the Lithuanian words are unfamiliar to most of us I think. I know I spent a LOT of time trying to find info on things that just isn't there, since their mythology isn't as popular as Greek, Norse, Celtic, etc. Like really it's the hardest part, hahaha. 

IMC - Good choice. <:

**Comment by vegax87** [comment]
I don't understand why the string ETC_20150312_002352   바이보라의 날개 has been translated in ByBora's Wings.
Bing translates it in "Buy Purple wings", in fact purple in korean is  보라색 (bo-ra-saek); 자주색 (ja-ju-saek)

**Comment by Sunaries** [comment]
Because the name is most likely derived from an NPC or object. We don't know yet, because we can't play the game nor data mine the client yet. It definitely isn't "buy purple wings".

**Comment by Nagoda** [comment]
I'd like to ask for opinions about some of the "Please defeat" text found in the ETC file.

There are at least several dozen lines containing the command to "Please defeat X monster".
For example, "가고일을 처치하세요!" is currently translated as "Please defeat Gargoyle!" , and has two possible problems that I can see.

The first is that while the original text does seem to literally say "Please", I think it sounds a bit strange in English considering the context. I'm assuming most of the ETC file is comprised of on-screen notifications, quest directions, and tooltips rather than actual NPC dialog. I don't know enough about Korean to know if it's typical for a game user interface or a quest direction to use such polite language, but in an English interface we tend to expect the language to be very direct, instructional, and commanding. The interface doesn't need to politely ask you to do something, it should simply tell you what you need to do in order to proceed. So my suggestion here is that we translate lines like this without the "please".

My second concern is a little more subtle... I'm sort of cobbling together an understanding here based on machine translators and wiki websites, but it's unclear to me whether a line like "Please defeat Gargoyle!" is telling me to kill an individual monster that is literally named "Gargoyle", or if it's telling me to kill a member of the Gargoyle 'species'. Someone who can easily read the Korean might have to enlighten or correct me, but if we have a bunch of bosses that are named after mundane *types* of monsters, then I think it would be better to give them unique names(though this is something IMC would have to probably decide on themselves.) 

To put it succinctly, if text appears on the screen that says "Defeat Gargoyle!", and then a single boss monster named "Gargoyle" appears, then that monster probably should have been given a real name, or it should instead be written as "Defeat the Gargoyle!"

**Comment by Sunaries** [comment]
병사 is a common function that NPCs have in the game. 

This can be translated as guard or soldier... Hm.

**Comment by imcgames** [comment]
바이보라 is a name, not a common term  :)

**Comment by vegax87** [comment]
there's a hidden class name that I can't translate: ETC_20150317_006276 시마도사
in korean is spelled "simadosa" but I checked the wiki and I can't find that class.
