### ISSUE TITLE
Change Doppelsoeldner to Doppelsöldner (Debate on Umlaut)

### ISSUE THREAD

**Issue by Sourpusss** [Treeofsavior/EnglishTranslation#510]
In the wiki, the job for Doppelsöldner is spelled Doppelsoeldner, and the various translation files have a handful of different spellings.  I feel like we should change the wiki entry to something proper, of which should either be Doppelsöldner or Doppelsoldner.  Technically, the O with an umlaut is the most correct, but I don't know if this will cause any formatting issues, as well as being annoying to type for some.  However, the current wiki entry is not correct.

For reference: https://en.wikipedia.org/wiki/Doppels%C3%B6ldner

So, should we just settle for Doppelsoldner? Or be proper with an Umlaut (Doppelsöldner)?

**Comment by TOSBase** [comment]
See also: https://github.com/Treeofsavior/EnglishTranslation/issues/133

**Comment by ensata** [comment]
Um, what? The version on the wiki is correct. We're meant to translate it to English, so we should be using the English alphabet - the umlaut is not part of that, so you check for a standard method to convert or romanise German, and it just so happens that one exists: add a letter 'e' after it. There's nothing to really debate? 'Doppelsoldner' is the one that's least correct, but that one's also okay, since the umlaut mistake is common.

**Comment by Sourpusss** [comment]
My bad - didn't do enough research.  Thank you, TOSBase.

**Comment by Flevalt** [comment]
When in doubt:
oe = ö
ae = ä
ue = ü
Schwarzer Reiter

**Comment by vtange** [comment]
Doppelsoldners replaced.

**Comment by ensata** [comment]
@vtange , you just did the _exact opposite_ of what was established in the Wiki.

**Comment by ttgmichael** [comment]
Which made me confused because it actually got merged xD.

Well, it is up to IMC to decide whether the game should label the class Doppelsöldner, Doppelsoeldner, or Doppelsoldners. We as translators are merely giving our suggestions on how to make the best "international English" version so they can translate the non-English versions more easier. If they want to change it back to Doppelsoeldner, feel free to do so. I would only think that changing it to Doppelsöldner means we limit the type of fonts we can use in game as certain fonts don't support accented characters :P.

**Comment by vtange** [comment]
Gah! I got the impression we wanted the special "o" in since we were doing special characters for Ellipsis (...) anyways. Fixing them back. My bad.

**Comment by Sourpusss** [comment]
Doppelsoeldner is the most correct, when not using special characters.  Additionally, to support this, we ARE NOT using unicode ellipses (as vtange just thought).  Umlauts should be vowel+e, and ellipses should be three individual .'s in a row.
