### ISSUE TITLE
Sticky? All about the Great Disaster.

### ISSUE THREAD

**Issue by vtange** [Treeofsavior/EnglishTranslation#542]
It seems that a LOT of lines everywhere refer to a disaster day.  

Since this is such a MAJOR event, let's get all the names/facts we know about this disaster in one place, so we all can get the context better and keep things coherent for all the files.
If it seems we have too many ways of calling the same disaster, we should work on thinning them down here in this thread. I've only touched ETC.tsv and QUEST.tsv thus far, so:

Names of disaster day:
"Vegetation Disaster" -> ETC.tsv
"Great Plant Cataclysm" -> ETC.tsv by ttgmichael
"Day of the Divine Tree" -> QUEST.tsv
"Divine Day" -> QUEST.tsv
"God Beast Day"->QUEST.tsv
"Great Earthquake"->QUEST.tsv

What happened on Disaster Day:
1. The Goddesses fled/went into hiding.
2. Austras Koks (the big tree) sprouts from the capital city, growing very rapidly i presume.
3. A giant earthquake.
4. A sudden increase of demons and monsters throughout the kingdom

I will add to the list any info you guys comment in so hopefully in the end we can picture everything about this event well.

@imcgames You could have someone monitor the stuff posted here to make sure we didn't completely misinterpret anything. This way we can make sure we got this core element of the game right.

**Comment by Flevalt** [comment]
I mostly deal with the lvl200 Quests and they refer to it as the "Day of Divine Tree" there. 
I left the name untouched as I saw a discussion about it in one of the issues. 
There was not much information concerning the Disaster in what I've read. 
I can mostly give some other minor infos that might help with understanding context in some cases.

-> The disaster was exactly 4 years ago from the time the story is set in
-> There seems to have been another big disaster in a place called the Wastelands 600 years ago
-> Phenomena turning people into stone called Stone Frosts were created a few hundred years ago due to a Rebellion by someone named Ruklys. Since the disaster 4 years ago, these phenomena's appearances have become harder to predict
-> The player seems to belong to a group whose members are referred to as Revelators. 
-> A Kingdom Army exists who seemingly uses their soldiers rather carelessly as cannon fodder
Edit: And they are in such dire need of more men that they hire thieves and refugees too.
-> There is an order of knights called the Kalis Knights who support the Kingdom Army with manpower and supplies
-> There are powerful demons referred to as Monarchs. Namely Nuaele, Houberg, Taumas, Bloot and Naktis.
-> There are owl statues spread throughout the lands, who apparently guide souls
-> Either the disaster is also called "Medis Diena" or that is a false translation

**Comment by emailboxu** [comment]
There's no indication whether all of these refer to the same thing. The Great Plant Cataclysm and Day of Divine Tree could be different events.
