### ISSUE TITLE
Wiki Terms

### ISSUE THREAD

**Issue by AndronicusTOSGame** [Treeofsavior/EnglishTranslation#56]
Was going through the terms and found these errors that the staff might consider fixing. 
https://github.com/Treeofsavior/EnglishTranslation/wiki/2.%20Reference

Format: 
Korean Word - Original English Word - Suggested English Word
or
Original English Word - Suggested English Word

Class:
쿼렐슈터 - Quarrelshooter - Quarrel Shooter
도펠죌트너 - Doppelsoeldner - Doppelsoldner
크리비 - Krivi - Krivis
사두 - Sadu - Sadhu
References:
en.wikipedia.org/wiki/Doppelsöldner
lt.wikipedia.org/wiki/Krivis
en.wikipedia.org/wiki/Sadhu
These are all their original spelling, and I suggest we stick to it :)

Map:
심문실 - Investstigation Room - Interrogation/Investigation Room
페디미안 직할령 - Pedimian Territory - Fedimian Territory
수정광산 1층 - Crystal Mine 1st Gallery - Crystal Mine 1st Floor
수정광산 2층 - Crystal Mine 2nd Gallery - Crystal Mine 2nd Floor
수정광산 3층 - Crystal Mine 3rd Gallery - Crystal Mine 3rd Floor
수정광산 2광구 1층 - 2nd Mine Lot 1st Gallery - 2nd Mine Lot 1st Floor
수정광산 2광구 2층 - 2nd Mine Lot 2nd Gallery - 2nd Mine Lot 2nd Floor
칠채고원평 - Seven Hues Mesa - Seven Hues Plateau
하늘지친 고원 - Skyweary Mesa - Skyweary Plateau
큰고립 고원 - Grand Isolated Mesa - Grand Isolated Plateau
마당 고원big - Grand Yard Mesa - Grand Yard Plateau
"Mesa" is a Spanish word for Plateau, since there are other terms that are using the word "Plateau" for 고원, I believe the developer should look into which word accurately describes the map. Highland, Plateau, Mesa or etc. 

Equipment: 
망고슈 - Maingauche - Main Gauche
콰다라 - Guaddara - Quaddara http://commons.wikimedia.org/wiki/File:Quaddara_sword_and_kindjal_dagger.jpg
병사의 숏 로드 - Soldier'S Short Rod - Soldier's Short Rod
병사의 라이트 보우 - Soldier'S Light Bow - Soldier's Light Bow
병사의 우든 클럽 - Soldiers Wooden Club - Soldier's Wooden Club
Morningstar - Morning Star
Godendag - Goedendag - Ref: en.wikipedia.org/wiki/Goedendag
Baltas Morningstar - Baltas Morning Star
로우 폴쳔 - Low Falchion - Crude Falchion
로우 카스카라 - Low Kaskara - Crude Kaskara
I don't think "Low" is the right term to use for lower grade items. I suggest to use "Crude" instead. Also, "Coarse", "Crude" and "Low" are all three terms used in the equipment section. Perhaps we should standardize it if they are all the same meaning. 

Item:
이동속도 증가 포션 - Potion Increaing Movement - Movement Increase Potion
빅 코카트리스의 심장 - Heart of Big_Cockatries - Heart of the Big Cockatrice
붉은 케파의 줄기 - Stem of Red_Kepa - Stem of Red Kepa
붉은 케파의 결정 - Crystal of Red_Kepa - Crystal of Red Kepa
씨드미아 꽃가루 - Seedmia Poleen - Seedmia Pollen
러바인러바 산성 수액 - Ravinelerva Acdic Sap - Ravinelerva Acidic Sap
빅 코카트리스의 부리 - Big_Cockatries Beak - Big Cockatrice Beak
코카트리스 가죽 - Cockatries Leather - Cockatrice Leather
코카트리스 깃털 - Cockatries Feather - Cockatrice Feather

If I found more errors I'll let you know. Suggestions for terms highly welcomed. 

Fixed:
"Companion Item" and "Costume" link to the same page.

**Comment by AEJung** [comment]
The original Korean is literally "ro-uu," so it is correct.

**Comment by imcgames** [comment]
Thank you for the suggestions, we've updated the class and wiki link first :)

**Comment by AndronicusTOSGame** [comment]
Yeah I understand AEJung. Maybe 로우 폴쳔 makes sense in Korean, however "Low Falchion" sounds pretty awkward in English. My (native Korean) translators suggested "Crude" instead for better English experience. 

I've updated the first post for more errors on "Map" section

**Comment by imcgames** [comment]
The 'Map' names are subject to change as development is in progress so we'll be updating it with new names soon

**Comment by Nagoda** [comment]
If 로우 just means "Low" and is meant to signify that the item is of poor quality, I definitely agree that "Crude" is much better.

**Comment by AndronicusTOSGame** [comment]
- Updated first post with more "Item" related spelling errors. 
- Created Fixed category

Agree with Nagoda

Also, "Coarse (조악한)", "Crude (조악한)" and "Low (로우)" are all three terms used in the equipment section. Perhaps we should standardize it if they carry the same meaning.

**Comment by AEJung** [comment]
You agree with Nagoda agreeing with you? This GitHub wasn't created to suggest how IMC rename their items, it's for a more-or-less direct translation. Native Korean vocab is pretty limited in that they have fewer words to describe more things. The beauty of the English language is that there typically so many ways to say the same thing, and it's usually best to avoid redundancy in writing English. Since 조악 describes either crudeness or coarseness, either translation is fine. And since they went out of their way to specifically give the weapon another name besides 조악, I doubt they wish to call it that. These are names, not a sort of stat that affects your character in anyway that would require standardization.  

Also while "mesa" is Spanish in origin it has also been adopted into American English. If anything IMC should go through and add more variety to the naming schemes. Highland would be another good translation for 고원. Suggesting any sort of standardized naming scheme is rather ridiculous, especially considering how creative and imaginative IMC has been with this game thus far...

**Comment by Nagoda** [comment]
Maybe we can come up with a different translation for 로우 than "Crude", particularly if they are also using another prefix which more directly translates as Crude, but sticking with "Low Weapon" is definitely plain wrong. The word Low is never used to describe objects in that way, and a person is more likely to think it has something to do with the item's relative height to the ground than anything to do with quality. 

Maybe there isn't a perfect word to capture exactly what the designers at IMC were thinking when they named a low level sword, but it's probably more important to get it close enough and make it still sound palatable to English speakers, rather than attempting to preserve(at the cost of comprehension) some vague sentiment the original Korean word had as it travels across the language barrier.

**Comment by AEJung** [comment]
What...? Low means many things.... Are High Bishops named such that they are tall? It's referring to the fact that the dagger is low rank/low quality/low value/low grade without being specific as to which. Again, the original word is Konglish, it is literally the English word written in hangeul. It's a grave mistake to dumb down names/dialog for people who would assume since the dagger or sword is low because it is close to the ground...... Not to mention that those weapons could very well be crafted items. Meaning people are capable of naming them whatever they wish, so the base names are of little consequence.

**Comment by Nagoda** [comment]
You will find all kinds of obscure and antiquated usages of words when you start poking around religious language and the hierarchies of Churches, and you will have a very hard time employing those same usages in almost any other context. Start calling someone the "High President", or the "High Mayor", or the "High Principal" and people will look at you funny.

Low is used almost exclusively to refer to the quantity or frequency of something, or as a descriptor of elevation, and when it does refer to the quantity of something, that "something" is present in the sentence. Any other use is going to be highly specific.

Koreans appropriating and using a phonetic version of an English word does not mean that the Korean usage is now accepted vernacular in English. I understand that the low is referring to the quality, and it would be acceptable usage if we translated it as "Low Quality Dagger", but writing it as "Low Dagger" is as wrong as "I have a low car", "That's a low house", "These clothes are low". It sounds awful even if it's possible to infer what the person is trying to say. No native English speaker talks like this, I don't know what else to say.

And before we start talking about how "grave" this matter is, let's all relax a little bit and acknowledge this is probably way too much debate over the precise word we should use to say "this sword is a bit crappy".

**Comment by AEJung** [comment]
This is a game taking place in an antiquated time period. Don't treat it as the dialog should be taking place in the modern world. People that go around speaking like Eddard Stark or Gandalf are going to be looked at oddly, too, but that doesn't mean it isn't a good fit for the fictional time period of the book. The dialog should sound a bit old, a bit flowery. It's not uncommon for equipment or monsters within games to be dubbed as "High ____," so there's really nothing terribly wrong with doing the opposite. Is it bland? Yes, but again it's probably just a generic placeholder for players to rename. 

A better name for it would probably be "Modest" but "Bit Crappy Kaskara" has a nice ring to it, also.

**Comment by MarkofKain** [comment]
I would have to agree with something more precise than "Low".

When translating, you shouldn't look for the most literal translation. Especially, as you say AEJung, when that language is limited by its vocabulary to describe things. Say you wanted to translate the color cyan from a hypothetical language to English. But that language only has the word that means Blue. Would you translate that color as blue, or more specifically and correctly as Cyan?

**Comment by Nagoda** [comment]
I understand your point AEJung, but I suspect that they did not write "Low" because they were trying to convey a sense of antiquated and flowery language, but rather it was an accident of the designers' tenuous grasp of English (the reason Konglish exists), or of them not thinking about how it would eventually sound if translated into English again. Anyway, let's try to move forward.

I think "Modest" would be acceptable, and I would put forward "Simple" as another possibility.  Simple even has a slightly negative connotation, appropriate for describing an unimpressive or humble piece of equipment.

**Comment by MarkofKain** [comment]
Crude, inferior, mediocre, common.

**Comment by imcgames** [comment]
Thank you all for your concerns regarding our equipment translations. 
We respect everyone's points and views and to prevent further confusion, we have decided to revamp some of our equipment names. 
We will be updating our wiki reference with the new names soon :)

**Comment by imcgames** [comment]
Equipment section has been updated

**Comment by AndronicusTOSGame** [comment]
I kept seeing the word "Dunkel" in 
https://github.com/Treeofsavior/EnglishTranslation/blob/master/ITEM_en.tsv
Can anyone enlighten me with the meaning of "Dunkel"?

**Comment by Nagoda** [comment]
Dunkel is German for "Dark"

 It doesn't seem too out of place to me considering we've got class names like "Doppelsoldner", and "Schwarze Reiter". The game seems to draw inspiration from a pretty wide scattershot of world cultures and languages.

**Comment by ArkKnight** [comment]
Suggested Changes: 
Movement Increase Potion > Movement Speed Potion / Swiftness Potion

**Comment by Waterfighter** [comment]
Minor suggested changes for Costume:

크리비 코스튬 Krivi Costume - Krivis Costume
사두 코스튬 Sadu Costume - Sadhu Costume
고글 Goggle - Goggles
흰꽃 머리핀 White Flower Hair Pin - White Flower Hairpin
천사 날개 장식    Engel Wing Decoration - Angel Wing Decoration
세련된 안경 Polished Glassess - Polished Glasses
이세계의안경 Ultramundane of Glassess - Ultramundane of Glasses
안경  Glassess - Glasses
유니콘 뿔   Horn of Unicon - Horn of Unicorn
메이드 머리띠 Maid hair band - Maid Hairband
버블스틱    Buble Stick - Bubble Stick

**Comment by imcgames** [comment]
Thank you, Wiki has been updated with your suggestions :+1:

**Comment by dlam** [comment]
@AEJung @MarkofKain @Nagoda I just came across the same problem while proofreading existing translations.

You're right that the goal of this repo is to provide direct translations, and not design new names. However, we are providing _direct_ not _literal_ translations of item names. Literal translations that come out awkward and / or vague should be replaced with something that is more true to the intended meaning.

E.g., "Low Bastard Sword" is awkward in English and should be replaced with either "Crude Bastard Sword" or "Low-grade Bastard Sword".

Also, I'd like to point out that it's worth standardizing these kinds of things, especially when translating out of context. For example, if an NPC tells you the reward for a quest is a "Crude Gladius", but you instead received a "Low-grade Bastard Sword", is objectively a bad thing.

See https://github.com/Treeofsavior/EnglishTranslation/issues/237.
