### ISSUE TITLE
Feedbacks/Suggestions

### ISSUE THREAD

**Issue by imcgames** [Treeofsavior/EnglishTranslation#60]
Hi guys!
It's been a few days since our test run started and for those who have been trying it out with us, we really appreciate your efforts. :+1: 
If you have any feedbacks and/or suggestions, we'd be glad to hear them so let us know through the comments below or you can create new issues if it calls for a new discussion :smiley:

**Comment by Sunaries** [comment]
Thanks for opening this project. I am flattered by your game and I love to contribute whenever I have spare time. 

It is hard to properly translate because of the little context that is given to us. Since Korean is a contextual language, I assume most of the text is a literal translation. 

Thanks!!

**Comment by imcgames** [comment]
We have updated QUEST_LV_100. We hope this would help you until gameplay is possible.

**Comment by xsicho** [comment]
I was thinking if I could start translating the translated English lines into other language by my own right now, since English seems to take quite some times to finish. If it helps, let me know and I'll start translating them from English to Thai in my own PC through a spreadsheet that could be copy-paste when you put up any other translation files after English.

**Comment by wazho** [comment]
> Modified

I changed this reply to a new issue.

[link here](https://github.com/Treeofsavior/EnglishTranslation/issues/115)

**Comment by imcgames** [comment]
For the first test, we will only be supporting English as the official language.

**Comment by mickeyjulian** [comment]
Keep them coming... :)

**Comment by unicorn00** [comment]
hello i'm a Tos close beta tester, thanks for this translation text, and i want to know how to use this text to instead the original korea version.if it can be instead, i can show Tos better on live,thanks~

**Comment by Sunaries** [comment]
In the current version of ETC.en, there are a lot of blank spaces that were previously filled by contributors on Github. @imcgames How come a lot of translated text done by our users have disappeared?

It feels demotivating to see my work and those of others disappear.

**Comment by imcgames** [comment]
You'll be able to use the translation files in the English Test version :)

Previously, ETC_en was filled with both machine and normal translations but it seemed to have caused some confusion for translators so we removed machine translation part from the file. Some lines may have been removed during this process and there were also some lines not properly translated which were removed as well. For those lines that were properly translated but accidentally removed, we will be adding them back later on. Sorry for the inconvenience this could have caused, we did not mean to demotivate you in any way :cry:
