### ISSUE TITLE
Too many people working on SKILL.tsv

### ISSUE THREAD

**Issue by vtange** [Treeofsavior/EnglishTranslation#631]
I was just reviewing the pull requests and found a number of newcomers working on SKILL.tsv.

New hands are always welcome, but please check existing pull requests before working. For example. @emailboxu had already worked a lot on the first 220 lines of SKILL.tsv and I am seeing a lot of people (@Vilifisaur just now) editing lines in that same range. Nobody likes merge conflicts so please slow down and check before you dive in.

**Comment by Ragunaga** [comment]
To be honest, I never even thought of that. Thanks for the post. Thankfully the (small) pull I made was in the 1000-1200 range.

I'll be sure to look out in the future.

**Comment by ensata** [comment]
You do realise that you're the one who caused those merge conflicts back then, right? I wrote a list explaining the rules to avoid it because of you. And you're still making your pull requests larger instead of making new atomic pull requests.

And now newcomers don't seem to be checking for a contribution guide, again. Not surprising.

Since I rushed it the first time, I rewrote the basic GitHub guide this morning, and it's here: https://github.com/ensata/ToS-en-fork/blob/notes/GitHub_Usage.txt

**Comment by Ragunaga** [comment]
No I don't realize that. And I honestly still don't realize how/when I caused that. 

I'm sorry for whatever problems I've caused, and will make sure to re-read all the guides indepth again.

If I edited a line, in a range far from what other people worked on, how did that mess it up?

**Comment by ensata** [comment]
I meant vtange. You're fine.

**Comment by vtange** [comment]
I know I caused a lot of conflicts when I first started @ensata. Sorry if that bugged you. I just want to prevent people from making the same mistakes I made before. That's all.

For the most part now I've been always checking other pull requests and making a mental note of what ranges to avoid before working.

**Comment by emailboxu** [comment]
I'd personally reccomend against putting up PRs on the weekend as IMC won't update until the Monday after, increasing the chance of conflicts.

**Comment by ensata** [comment]
There are far, far too many keywords in Skills.tsv being changed right now that has major implications in describing the game mechanics accurately. I thought it was bad enough with emailboxu wanting to change "Attack Area" to "AoE", but this is going to get worse before it gets better. The "Status Point" and "Attribute Point" issue was never even resolved, and now it's been skipped over.

Personally, I would **strongly** recommend @imcgames to reject most, if not all of the name changes and start building a game mechanic glossary like with the map names and whatnot. 

This is getting close to the breaking point that I've been expecting, where there are simply far too many cooks in the kitchen for the project to stay public and continue in the way it's been going. It needs to be figured out.

**Comment by wlghksdl2** [comment]
Seems like there are too many editors and too few translators.
Curious how many translators are working on this project at the moment.

**Comment by vegax87** [comment]
In the past months there were threads posted by imcgames like this one: https://github.com/Treeofsavior/EnglishTranslation/issues/79 to prevent merge conflicts and allow only authorized people to commit their lines, we need one for SKILL.tsv
I was working on SKILL.tsv too but @emailboxu preceded me on almost the same lines, so I stopped working on my pull request.
Seriously, if a translation file is messed up it could crash the game client, International CBT is near so let's avoid game crashes :)

@ensata :
- Attribute Poins are officially Attribute Points and not Status Points.
- It's better to leave Attack Area as it is, same thing for Splash, because a new player doesn't know what AoE means, expecially if you want to translate it in your mothertongue.

**Comment by Ragunaga** [comment]
I'm of the opinion AoE should be kept as Attack Area or Area of Effect.

I know for sure when I started playing MMOs, most of these terms bothered me for awhile.
