### ISSUE TITLE
Avoid pull requesting till the weekend ends or IMC clears the current ones. 

### ISSUE THREAD

**Issue by Chaosbelow** [Treeofsavior/EnglishTranslation#657]
There is a lot of pull requests currently, at the moment of this post there is 50. A lot of people keep editing the same first 100 lines of a file and changing the wording. Not to mention all the merge conflicts that are bound to happen when people make the same PRs changing the same lines. For now please wait until IMC has cleared the current PRs. Once they are clear then you can go back and check if your edits have already been done by someone else. Especially Skill.tsv...

Anyone else agree? We need more guidlines since there is an influx of translators. I'd vote to try and avoid making PRs on weekends, if possible. Especially the amount there currently is... At the very least,  please check other peoples PRs for the files you wish to edit. Someone could have already worked on the lines.

**Comment by Ragunaga** [comment]
It's not that we need more guidelines, we just need a way to get people to read them upfront and understand them before editing.

They are a bit hidden atm.

Edit; But I don't mind waiting till their business hours resume, and they update the master branch.

Edit 2; Made one more pull request that I had been wanting to, after triple checking line numbers and making sure no one had came near that range..

**Comment by ghost** [comment]
The guidelines are a bit messy but I and others managed to read through them and the issue posts to figure out where the project was and what way people wanted things done. How about a big sign on the front page shouting "STOP. Read and reread the guidelines and issue posts and wait 24 hours before touching anything."

Also, I agree, pull requests on the weekends is a bad time.

**Comment by Rezken** [comment]
I've already seen people editing stuff that I did edit before them.
Everyone should read the pull requests of the others before creating one, making sure you don't edit stuff that has been done already.

**Comment by MystesofEternity** [comment]
This is quite arguable. It was indeed part of the guidelines that an issue must first be made regarding which lines will be worked upon before any work on translations and pull requests be made. 

This sort of methodolody is actually quite effective IF ONLY everyone was following it. Something like indicating in the title of their issue which file/s and line/s they are going to work upon so that no one else would make a mess whenever everything is merged in the end. This also helps everyone in finding which parts of the whole big pile of files and lines are not being worked upon because it certainly is 10x more efficient in browsing through the issues and being able to use CTRL+F to ease the pain of finding the specific file which is your target for work. If you compare browsing through issues and browsing through pull requests, there's certainly a clear difference in efficiency.

If only it was clearly indicated in the forums or somewhere very eye catching :x

**Comment by ttgmichael** [comment]
Haha, usually I just wait until all the pull requests are pulled, then I start making edits/PRs again. 

For now, we can only wait and see what IMC wants to do with that much PR's ^^.
