### ISSUE TITLE
"You are the Revelator or a Revelator?"

### ISSUE THREAD

**Issue by ttgmichael** [Treeofsavior/EnglishTranslation#755]
Hey everyone,

I wanted to ask what are your opinions on translating Revelators. To me, it sounds like: a Revelator since there are so many people who dreamt of the Goddess(es?). IMO the story kind of treats Revelators as synonymous to an Adventurer.

And for the plural form, would it then be "the Revelators"? or just "Revelators"?

**Comment by cordogames** [comment]
Depends on the context I'd say, IE:

QUEST_LV_0100_20150317_000217   Maybe the person the Goddess sent was you.{nl}You're the most merciful person I've ever seen among the Revelators.
QUEST_LV_0100_20150317_000286   Shouldn't Revelators go to Klaipeda instead of here?
QUEST_LV_0100_20150317_000304   The bishop also dreamed of revelation.{nl}He said to send the Revelator to Crystal Mine.{nl}
QUEST_LV_0100_20150317_005453   Romas says he had to bury a Revelator once so don't be over confident.{nl}Kill 15 monsters nearby within 2 minutes and prove that you're not weak.

All these instances of (a/the) Revelator(s) seems to be used properly in context.

**Comment by ensata** [comment]
This has come up before (https://github.com/Treeofsavior/EnglishTranslation/issues/527) and I think part of it is running into a communication issue or a writing issue with imc, since imc's explanation makes the usage confusing.

There really needs to be a better sounding word than "Revelator"... but if you replace it with - for example - "Hero", or "Chosen One", then it should make a bit more sense: The word seems to have the same intention. 

The player thinks that they're _the_ hero, but the NPCs immediately lampshade it and point out that everyone coming into town is crazy and saying the same thing, so what's meant to be a title is heavily diluted and generic. So yeah, I guess you can also think of it as "Adventurer".

**Comment by Ragunaga** [comment]
As I said in the thread on the official forums;
"I don't know, Revelator seems kind of closer to home in this context.

And it just feels better to me personally.

He doesn't dream of himself saving the goddess, he is not bestowed a prophesy of him saving the goddess. He is bestowed with a revelation, that he is ABLE to help, that he CAN help, that he doesn't have to just sit around and hope someone else fixes it. Or to pray to another god to fix it. That it's time for him to do something himself."

I think it's perfect.

**Comment by Staryx** [comment]
yup, the word Revelator seems to save us and sometime we're called Saviors~ Both perfect for ToS

EDIT: If we tried using the word Adventurer, it kinda suggests we are people who came about to the game unknown to what is happening around us and meaning we didn't get the dream

**Comment by ttgmichael** [comment]
@Staryx No, I didn't mean that we should replace Revelator to Adventurer. Rather, I want to know what everyone thinks about the article before "Revelator" (the Revelator or a Revelator) as the Korean text doesn't fill it in, and we are stuck with an awkward "the" every time you read the main quest dialogue.

@cordogames Shouldn't QUEST_LV_0100_20150317_000304 be:
The bishop also dreamed of a revelation.{nl}He said to send Revelators to the Crystal Mine.{nl}
To send "the" revelator means there is only one true Revelator amongst the Revelators (which is your character). But we can see in the game that every Revelator gets sent to the mines, so shouldn't it be "Revelators"?

The other lines seem correct. I guess when we are referring to multiple Revelators, "the Revelators" or "Revelators" are used, but singular usage is "a Revelator"?

**Comment by ttgmichael** [comment]
Ok I'll be closing this issue; I think the final answer to this issue is:

It depends on the context as stated by @cordogames :+1:
