### ISSUE TITLE
Game Terminology and Syntax

### ISSUE THREAD

**Issue by Nagoda** [Treeofsavior/EnglishTranslation#776]
After playing the beta, I've encountered some terminology that appears in parts of the UI and various game systems that need some adjustment, some of which we can fix through pull requests, but some might require assistance and approval from @imcgames to change. I thought making a thread to bring up and discuss things like this would be a good idea.

**Damage Types**
ToS uses a system for having multiple types of damage that should be somewhat familiar to many players of RPGs, but the terminology it uses is sometimes inconsistent or odd sounding. More specifically:

The game uses "Hit" damage type on skill descriptions, "Strike" damage on weapon descriptions, and "Blow +50%" to show when you are hitting an enemy weakness. Clearly, calling the same damage type three different things is really confusing to the player.

 I also am not a huge fan of any of these specific names. "Blow" damage just sounds strange. "Hit" and "Strike" basically mean the same thing, but the way these words are commonly used in English, almost any kind of attack "hits" or "strikes" the enemy. My suggestion would be to change the term to "Crush", "Impact", or "Blunt" type damage. If we absolutely must use one of the hit/strike/blow already in the game, "Strike" is probably the least bad.

"Stab" type damage has a smaller issue. The game does use "Stab" consistently, and it's clear enough what type of damage it's meant to represent, but I think "Pierce" is a far better word for this damage type. The word "Stab" is associated more with hand weapons like daggers and knives, and it looks pretty silly to have a Bow that "Stabs" enemies with arrows. The word "Pierce" is clear enough that it easily tells us what type of attack it is, while still being flexible enough to sound natural whether you're describing daggers, spears, arrows, or magic.

"Slash" damage needs no change.

Most of these can be fixed through data editable in the tsv files and pull requests, but I think IMC should approve any new terms we come up with since they will affect many skills and items across the game. I haven't been able to find the "Blow +50%" or "Stab +50%" popups in the tsv files, so that might be a graphic which IMC would have to change.

As a related issue, in the F3 skill menu, the game tags some skills with a red "Hit" banner in the upper left corner. Players have told me this is supposed to tell people which skills are most popular with other players, but right now it just adds even more confusion to the "Hit" damage type, since players might easily think it has something to do with how the skill works. I think the easiest fix here is to change it to be "Hot" so that it's consistent with the similar banner that appears in the Class Advancement menu.)

**Counting with "ea"**
_Example: "Kepa Stem 2 ea Obtained" or "Max Socket 1 ea"_

This is an odd bit of translation that has always bugged me, has been around since Ragnarok at least, and I'm sure has made it into other games. I truly don't know if this is a Konglish artifact or what, people say the "ea" is meant to represent "each", but the usage makes little sense in English. The only acceptable use that comes to mind is in player-run shop menus where buying or selling an item for "x silver each" makes sense. There are many lines in the TSV files with "ea" usage, but it's very difficult to test which line in the file corresponds to what in-game, even with the real-time tool. One easy change that could be done is to modify

ETC_20150317_002445 {Count} ea obtained 
to
ETC_20150317_002445 x {Count} obtained
so item pickup lines would read as "Kepa Stem x 2 obtained"

There are many other "ea" lines in the tsv files, but this one is probably the most frequently seen and most easily changed. I have tested this change within the game and think it looks good with how the item pickup notification is formatted.

**Summary**

-Consistency between "Hit/Strike/Blow" damage types, suggest unifying them all as **"Crush"** damage type. IMC assistance possibly required to change "Blow +50%" combat text.

-Suggest changing "Stab" damage type to **"Pierce"**. IMC assistance possibly required to change "Stab +50%" combat text.

-Change the red "Hit" banner that appears on some skills in the F3 menu to read as "Hot" for less confusion and to match the Class Advance menu. IMC probably needs to edit this graphic.

-Eliminate usage of "ea" as a counting marker as much as possible, except in specific cases where it makes sense, such as shop menus. Replace "ea" with "x" where necessary, 

This is far from a comprehensive list, I'm sure there will be more to add in the future, and it might take some time to whittle away at the more subtle problems like "ea" counting. As always, other people are welcome to add their thoughts and share any additional items which might be relevant.

**Comment by ensata** [comment]
Consistent terminology, nouns and other keywords is actually a pretty major issue from what I've seen. 

For the game mechanics specifically, I would generally suggest studying the commonly accepted terminology in western RPGs for an idea of what western players will understand. I don't just mean playing some video games, but also the grandfather of the RPG: D&D. It _always_ returns there, at some point or other. 

For the standard triangle of Physical Damage types, those are: **Bludgeon/Blunt; Slash; Pierce.**

From that, you might change up the synonyms based on the game's actual skills, but it's not very different. Calling it _'Crush'_ instead of _'Blunt'_ is... well, I'm not for or against it, but it all comes down to the types of skills in the game, and whether that word comes up somewhere else. I would consider whatever words picked to be reserved, which means that you should avoid using those words as much as possible, to avoid confusion between a request for a player action, and writing flavor - like what you pointed out with "Hit".

Anyway - 'ea' is actually meant to be an abbreviation of 'each', but the period is missing for some reason. 

The alternate word would be 'piece(s)', so that the full blurb would be "2 pieces obtained" or something. The actual problem though, as you pointed out in the example, comes in the construction of the sentence and the word order. I think there are actually several other places where the word order problem comes up with the dynamic sentences, but I can't really remember all of it.

**Comment by ttgmichael** [comment]
haha, I also was wary of these term consistency problems. 

Damage type terms should be : Blunt, Slash, Pierce; but since gun damage would be considered a "Blunt" damage, we might want to consider using the term "Impact"?

I would think making it [item] x [number] would be nice; someone should try it and if it's good, we should definitely go for that. Or, we would need to use "pieces" like what ensata suggested. I might go a step further and shorten the word to 'pc.' if people are ok with it ^^.

**Comment by Nagoda** [comment]
"Impact" was another replacement I suggested, and I would definitely support it. It's flexible enough to make sense for any kind of unusual magic attack or bullet weapons that might do blunt damage.

I don't think "piece" represents an improvement over "each" really. Neither make much sense, abbreviated or not. If I pick up two swords from the ground, seeing "Longsword 2 piece obtained" is just as bad.

After doing a little research it seems that "ea" is the result of Korean grammar requiring a word for the type of thing you're counting (frequently "개", used for counting objects) and the English translation being shoehorned into that structure. There is also the challenge of being unable to pluralize the names of objects and needing a one-size-fits-all wording, so it's necessary to compromise with something like "Sword x 2" since we can't use "Swords", and "2 Sword"/"Sword 2" is no good.

There are probably many parts of the UI where the "ea" can just be removed completely without any "x" counter to replace it, and the words around it slightly adjusted if necessary, like the "Max Sockets" stat on equipment. Currently written as "Max Socket 1/2/3 ea", when it should probably just simply be "Max Sockets: 1/2/3". 

It's definitely going a bit tricky, since we need to work within the confines of the tsv files, the formatting of the game text, and each usage is a bit different.

**Comment by ttgmichael** [comment]
Well, I got some of the dynamic lines to look pretty legible so far. I'll try with RTT and see if I can get it as close to what we've discussed ;)

**Comment by Nagoda** [comment]
Thinking a little more on it, there's probably a unicode "x" that might be better for the "item obtained" line, just to make it a little bit more clear that it stands for multiplication. I'll have to try them in the editor to see which one looks best with the game font and formatting.

**Comment by Sunaries** [comment]
Regarding **counting with "ea"**: https://github.com/Treeofsavior/EnglishTranslation/issues/283

**Comment by Nagoda** [comment]
The round bracket notation mentioned in that thread also seems acceptable, e.g. "Kepa Stem (2) Obtained" or "Max Sockets (2)"

**Comment by ensata** [comment]
Huh, that's weird. I think I've seen it classified as 'impact' in some other game, but guns are usually classified as a piercing weapon.

Anyway, I didn't actually mean for you to consider 'pieces'. If you really, really needed to translate that Korean counter, that's the closest thing I can think of - but you don't really say it that way very often in English.

The unicode 'x' that you'd be looking for is probably the multiplication symbol - '×' - which I didn't put into my hastily assembled Unicode test. I just went in and checked if it would be rendered properly. (I also got lucky and snapped another typesetting problem.)

![Item popup](https://raw.githubusercontent.com/ensata/ToS-en-fork/notes/Typesetting%20Reference/item%20get.jpg)

Since this is a distinct part of the UI that's exclusively for items obtained, it's possible that you can cut out the word 'obtained', too.

But, you can now see another problem - the layout. Writing it just as _"Obtained: Item × 3"_ looks the best, but it doesn't work with the item popup right now.

**Comment by Nagoda** [comment]
I think guns in ToS are considered blunt because they're probably primitive firearms with spherical bullets, which don't really penetrate like modern bullets, so much as they just smash their way through whatever they hit.

Right, the ordering is pretty rigid because of how the popup graphic is formatted and programmed. 

I think the unicode multiplication x looks pretty good there. I do think we should keep "obtained", both for clarity, and also for aesthetic reasons because having some text in that window balances it out and makes it look a little nicer. I could also accept "found", "picked up", "looted", or any number of other words, but I don't think we need to spiral off into a brand new debate there.

**Comment by ensata** [comment]
I thought of that, but that's fictional logic for fairness - in real life, guns fell into a completely different class, and early firearms still trumped the arrow and bolt by a huge margin. I might accept it if it were a shotgun, but anyway - this is spiraling far into game design and storytelling, now.

Keeping the word 'obtained' is okay, but it's a temporary fix for the main issue of how the UI is oversized in some places, and could use a redesign to move the whitespace around. I'm pretty sure there's been feedback about the UI scale in the forums.

**Comment by ttgmichael** [comment]
The unicode 'x' looks the best! Keeping 'obtained' is ok too :+1:

**Comment by Nagoda** [comment]
As per @ttgmichael 's reminder in another thread,

To summarize and solicit final discussion on rules we can put into use :

The game uses a familiar system of various damage types with pokemon-esque strengths and weaknesses. The word for this mechanic in the Korean text is "속성" and IMC has indicated in the past that they were translating this as "Attribute", though it also appears inconsistently in the English script as "Property". This is a different system from the passive skill "Attribute" system, but that's a separate discussion and I intend to try to get that system renamed to avoid confusion.

We have identified two types of physical damage "Attributes" which have names that need to be unified across the game text and/or replaced with more fitting words.
- "타격" is inconsistently translated as "Hit", "Strike", "Blow", or "Impact" type damage within the game.
  "타격" should be unified and consistently translated as **"Impact"** across all game text.
- "찌르기" is translated as "Stab" type damage. To make the word better fit with the various types of weapons that will be listed as dealing "Stab" damage (Such as Bows and Spiked Maces), and to use more common terminology from English RPG rules, "Stab" should be replaced with **"Pierce"** across all game text involving damage types.

As always, I do not speak Korean so I am open to correction, and general statements of agreement or disagreement.

**Comment by Soukyuu** [comment]
My beef with "impact" is that it's doesn't have to be blunt to count as one. Also, people are more used to seeing "blunt". On the other hand, as was said already, the guns being classified as "blunt" would seem weird. Still, I'd vote for "blunt" in this case. 

Agreed on replacing "stab" with "pierce". The unicode multiplication symbol also looks quite nice for drops, and keeping "obtained" makes it appear less cut off (or rather, we fill more whitespace on the UI with that)

**Comment by Nagoda** [comment]
It seems we have basically universal agreement on "Stab">"Pierce"

I don't have strong feelings about what we call the bludgeoning type damage (not bludgeoning though, too long), I think most of the proposed options sound fine (Crush/Impact/Blunt). I would accept "Blunt" if other people don't have serious objections, and there is some benefit to "Blunt" having some precedence in Western RPG rules.
