### ISSUE TITLE
How to Apply Real-Time Translation Text to Github?

### ISSUE THREAD

**Issue by Clariche** [Treeofsavior/EnglishTranslation#780]
Hello,

I've been using real-time translation to make grammar/expression corrections throughout the game play, but I just have no idea how I can create a pull-request to upload the changes. Do I have to manually punch-in the revised lines on GitHub, or would someone kindly be able to explain to me how I can upload the files? Even on the "create pull request" page where I need to select two files to compare I don't know which ones I should be choosing.. (Yes, I'm feeling pretty dumb).

If anyone could help out, that would be much appreciated! I've been reading every single line over and over again to ensure they sound okay, and I really want to help out with the ENG client development!

**Comment by ttgmichael** [comment]
Have you used github before? You have a forked copy of this repository (although a bit old). You'll need to pull the current changes on this repository first before making a PR.

By using the Git bash:
1. going to your old git repository. 
   cd [to your git repository]
2. Enter: git remote add upstream https://github.com/Treeofsavior/EnglishTranslation/
3. Enter: git pull upstream master
4. if you encounter merge conflicts, look at your files for "=======", "<<<<<<", and ">>>>>>>". These will be places where Github could decide which lines are the latest (as you might have editted them while someone else has editted them as well). 
5. After resolving any conflicts push your pull changes to your own repository (which makes your repository up to date)
6. Now, you will need to drag your files from the game folders to your updated git folder. 
7. Please submit your changes 1 file at a time and if possible, under 300 line changes. It'll be hard to track the changes you made if you go over this limit.

**Comment by laurencee** [comment]
Few extra notes:
- If you have **changes in your repository** and there are **also changes in IMC repository** that you haven't got then instead of _git pull upstream master_ you will need to do _git rebase upstream/master_ which will replay your changes on the top of the IMC changes
- If you want to change multiple different files, each file should go in its own branch so you can submit separate pull requests per file.

If all of this is too hard you'd be better to submit your requests through the TOS base web translator: http://translator.tosbase.com/
