### ISSUE TITLE
Hasten the Project. Waive your claims to your work like this

### ISSUE THREAD

**Issue by vtange** [Treeofsavior/EnglishTranslation#838]
It seems that we have hit a legal roadblock in this project and the imcGames has stated they will not pull from anyone for about two weeks. That is going to freeze this project bad; there are already 73 and counting PRs and with those on standby most of us will be unable to do anything until imcGames pulls. That sucks because right now a lot of good edits can be made with the beta still fresh in our minds.

Unless we step up and dismiss any ideas of demanding future compensation for our work here when the game goes commercial, I don't think imcGames will lift a finger.

So how about we email imcGames at their email to tell them "Yes, you can sell your game with my translations and editing work" so they can start pulling again? Here is an example by me using @ensata 's example:

---

Hi IMC,

I understand from your new Readme file on the English Translation project on Github that there are worries about the copyright and ownership of my contributions to your project. I'd like to waive my ownership to my work to dismiss this worry and help unburden the project.

I, the individual using the username 'vtange' at GitHub (user page @ https://github.com/vtange), hereby transfer full and complete ownership to IMCGAMES CO., LTD. the set of translations and writings that were submitted and accepted into the "Tree of Savior Korean to English Translation OTC" GitHub project file repository (as found @ https://github.com/Treeofsavior/EnglishTranslation) that were made after the date of March 1, 2015 with no expectation or transfer of compensation, monetary or otherwise.

Thank you for making the game and giving Github users like me a chance to contribute.

---

...where you replace all links and instances of 'vtange' with your own name and links. Make sure you are thorough.

We can do this per account. This way imcGames can at least pull from the accounts that have waived their claims to their work without having to wait til the 23rd.

**Comment by vtange** [comment]
It might be best that imcGames close all open pull requests from users who had not done the above by the 23rd. After the 23rd we should put a big sign that says "you agree to waive ownership of your work when you contribute" and assume all work thereafter is clean.

**Comment by ensata** [comment]
Oh, I knew sending those BCCs were a bad idea. I don't think anyone really uses them, anymore. I sent those to ensure a few discrete witnesses, and I hoped that there'd be a few days of proper, quiet,  private deliberation by all parties. 

There are several options that can be taken by imc at this point, and it's something to think about. Some will damage the project, and some should let it become much better - but I was pretty sure that it couldn't continue like this.

Please don't use my "example" as a template. I don't know if it's correct, and there is some specific phrasing and intentional omissions. You're all supposed to think about it yourselves and send your own answer. I did mine more formally and made my decision for very specific reasons, but it's up to their lawyer to decide what counts as a verifiable statement. It doesn't always need to be fancy, it just needs to be clear and verifiable.

**Comment by ttgmichael** [comment]
Well, BCCing only a few discrete witnesses means the majority of contributors are left in the dark. I think it's better for it to be out in the open so that everyone knows.

As I don't have a template myself, I still used yours in my email. It's better than nothing I suppose xD.

Thank you for pointing out the legal risk still, @ensata! :+1:

**Comment by ensata** [comment]
Well, temporarily leaving them in the dark was intentional, because it's not my job to contact everyone. I shouldn't even need to do this. I've been a little generous, but I've still gone pretty far overtime for the amount I was willing to give for free.

**Comment by laurencee** [comment]
@vtange if they need people to sign some agreement then they need to simply state this in their readme/wiki like many other projects out there.

This isn't a new thing in the open source world, it's a very common problem when it comes to commerical software with open source components.

Here's an example from ServiceStack which is open source but sold commercially: https://docs.google.com/forms/d/16Op0fmKaqYtxGL4sg7w_g-cXXyCoWjzppgkuqzOeKyk/viewform

**Comment by ensata** [comment]
Yeah, well, I can only hope that they figure it out properly, since I wouldn't consider what's in the readme at the moment to be really sufficient, if at all. It's one semi-broken-English paragraph that's obviously a hasty response to the no-longer-discrete email I sent last night. It's still not a license... and I'm not really sure it's even a fully correct statement. I never even mentioned the other legal stuff that they messed up on, either.

**Comment by ghost** [comment]
Which email address of theirs shall we be using?

**Comment by laurencee** [comment]
Well they've updated their readme to state you only need to email them if you **disagree** with their right to the translation contributions.

If you agree with them then you don't need to do anything. :+1:

**Comment by Soukyuu** [comment]
I understand they want all their bases to be covered, but did anyone really expected any compensation for the work done here? I'm not that versed in the legal matters, but unless there is a contract, isn't it implied the work here is donated to IMCGames?

**Comment by laurencee** [comment]
@Soukyuu  It's not implied if they use it for commercial gains.

All repositories on here (should) have a usage license that determines how the code/content can be used.
That being said, I don't know if just the notification in the readme is enough legally speaking. Would need a lawyer to comment on that one, everywhere else that I've contributed to source code that'd be used in commercial products required me to sign an agreement.

**Comment by emailboxu** [comment]
I, the individual using the username 'emailboxu' at GitHub (user page @ https://github.com/emailboxu), hereby transfer full and complete ownership to IMCGAMES CO., LTD. the all translations and writings that were submitted and accepted into the "Tree of Savior Korean to English Translation OTC" GitHub project file repository (as found @ https://github.com/Treeofsavior/EnglishTranslation) that were made after the date of January 1, 2015 with no expectation or transfer of compensation, monetary or otherwise. These translations were made without expectation of compensation and are free for IMCGAMES CO., LTD. to use and/or modify as they please.

Just dropping this here in case of any legal difficulties.

**Comment by Ragunaga** [comment]
Honestly, IMC is handling this wrong. There's still a legal problem like this, and honestly, no matter what they do, there still is a legal problem with translations submitted before this. (As my understanding of copyright law goes.)

I'll just sit this here tho, because I have no problem with this and understood at the start this was voluntary.

I, the individual using the username 'Ragunaga' at GitHub (user page @ https://github.com/Ragunaga), hereby transfer full and complete ownership to IMCGAMES CO., LTD. the all translations and writings that were submitted and accepted into the "Tree of Savior Korean to English Translation OTC" GitHub project file repository (as found @ https://github.com/Treeofsavior/EnglishTranslation) that were made after the date of January 1, 2015 with no expectation or transfer of compensation, monetary or otherwise. These translations were made without expectation of compensation and are free for IMCGAMES CO., LTD. to use and/or modify as they please.

**Comment by ensata** [comment]
Yeah, as I warned them in private, I don't believe whatever update they do can be retroactive, unless that was previously permitted. Emailing them if you disagree can only apply from actions made from this point forward, and so everything before now needs permission, by either a license given to imc, or an outright transfer of ownership.  

Ugh, so much for keeping the details of my email private. 

**Please stop using my legal statement as a template.** I chose my words and intentions carefully for myself, and only for myself - surrendering my ownership is pretty different from giving them permission. There's supposed to be a lawyer to clarify this.

Also, seriously, @imcgames , you need to **slow down** and stop making lots of tiny edits to the legal stuff in public. _That's making it worse._ I'm pretty sure I said in my email that you need to take the time to just do it fully and properly in private. This cooldown from the CBT was perfect timing, and no one took advantage of it.

**Comment by Ekatrina** [comment]
I, the individual using the username 'Ekatrina' at GitHub (user page @ https://github.com/Ekatrina), hereby transfer full and complete ownership to IMCGAMES CO., LTD. the set of translations and writings that were submitted and accepted into the "Tree of Savior Korean to English Translation OTC" GitHub project file repository (as found @ https://github.com/Treeofsavior/EnglishTranslation) that were made after the date of March 1, 2015 with no expectation or transfer of compensation, monetary or otherwise.

Thank you for making the game and giving Github users like me a chance to contribute.

**Comment by Sourpusss** [comment]
Even though I doubt it matters, and I'll probably cease my editing until the 23rd or IMC announces they'll take a statement to authorize the use of an individual's work, I'll go ahead and authorize my work:

On the date of August 12th, 2015, I, the github user Sourpusss hereby authorize all my past and future contributions within the file repository accessed via the web link  https://github.com/Treeofsavior/EnglishTranslation to be used by IMCGAMES Co., LTD. as they see fit.  I expect no compensation for my work.

If there is a standardized authorization format that IMC can provide, I'll gladly fill that out.  I doubt any of this will have an impact before the 23rd, though.  I know they're trying to protect themselves here, but seriously, if anyone honestly expected compensation for their work here, they're asinine and / or extremely greedy.
