### ISSUE TITLE
CURRENT STATUS

### ISSUE THREAD

**Issue by Sunaries** [Treeofsavior/EnglishTranslation#850]
Greetings,

At this time I felt the urge to create an Issue regarding the current status of the Korean to English translation project of Tree of Savior. The first English beta has just ended and there are a ton of pull requests created. Since the CBT has ended @imcgames  has gone absent, but will check the GitHub repository periodically. As of right now, I will not submit any pull requests until a large portion has been reviewed and closed. 

This translation project needs priorities. There are no priorities right now and that means there is a little bit of chaos going on right now. Before I list the priorities that I want to cover, I will ask the dedicated contributors/translators to join Discord.
- **DISCORD**

[Discord](https://discordapp.com/) is a new VoIP app that is free to use. There are no costs for servers, accounts, etc. You can also use Discord from mobile apps, desktop apps, or just through the browser.​ It is a very good alternative to Skype. (Uses less resources than Skype) 

We have a few contributors in our server and we'd love to have more dedicated contributors to join us, because this is an efficient way of communicating with each other. 
There are separate text channels (ETC, ITEM, QUEST etc.) where discussion can take place about the respective translation files. 
[CLICK HERE to join the Tree of Savior Korean to English Translation OTC server.](https://discord.gg/0RoYSiES4f4zwAk8)
- **ISSUES ON GITHUB**

As I am writing this Issue, there are currently **41 open Issues**. Some Issues have been answered and some now. In order to avoid clutter on this GitHub repository, we need the authors of those Issues to **close** their Issue when it has been answered. Just looking at this list of 2 pages gives me a headache. Especially when some of those have been answered. Note that questions about whatever translation is correct can be asked on Discord provided that the contributor has joined the server.  
I don't know if this exists on GitHub, but an option I can think of is for @imcgames to give privileges to a trustworthy and dedicated contributor to close Issues. 
- **WIKI**

The [Wiki](https://github.com/Treeofsavior/EnglishTranslation/wiki) is a **very important** resource that needs to be used for this translation project. I have seen pull requests of contributors changing map names, monster names etc to their liking. (e.g. _Tower of Magician instead of Mage Tower, Starving Demon's Road instead of Starving Demon's Way, Bidotas instead of Vidotas etc._) 
Inconsistency occurs when this happens. **Inconsistencies needs to be avoided**. Therefore the Wiki needs to be updated since it is of utmost importance. Because when the Wiki is complete after IMC's approval, you can just link the Wiki page since that is the real deal. 

A lot of map names in Tree of Savior consist of Lithuanian etymology, so it is hard to pinpoint the exact translation. @Xenobius2501 made a useful Issue regarding this: https://github.com/Treeofsavior/EnglishTranslation/issues/581 
I hope that @Xenobius2501 and @imcgames can provide their help into this issue. I hardly know anything of the Lithuanian language, so it is difficult to give my verdict on it.

A dedicated contributor @ttgmichael has provided his GitHub to work on this problem. [Click here for his provided GitHub repository](https://github.com/ttgmichael/EnglishTranslation/wiki) 
I have made a special channel for the Wiki on our Discord server. If you would like to contribute, join us. Once this is finalized, we can simply submit the changes to @imcgames. They will review it and after approval put it on this GitHub repository as a useful resource. 
- **TRANSLATION & LOCALIZATION**

I have seen pull requests from contributors who changed certain NPC names or item names or something else because they were not familiar with it. This does not mean that you can simply change it to whatever you deem most appropriate. This is a **translation project** meaning that we should follow the spelling and meaning of the Korean counterpart. 
Tree of Savior is a game with a fictional universe meaning that you ought to meet characters whose name will confuse you or use items where you've never heard of it. 

Localization is part of a process where you localize/rewrite imported content from Korea, adjusted for audience/pop-culture reception. I agree that we should keep the flow in sentences as smooth as possible, but please stick to the original as possible. 
- **PULL REQUESTS** 

Right now there are **81 open pull requests** - You have to admit that is a lot, right? I've seen good contributions of users who changed many lines. However, I also encounter pull requests where I only see 1 or 2 fixes. Can you imagine that if we follow this procedure, the Pull Request section will get cluttered? This will only lead to confusion. **We need to aim for a better insight.** 

Do we need to set up a criteria for accepted pull requests? 
**Example**: Only pull requests with more than 10 edited lines gets reviewed. 
- **THE 'X' MARKING**

Just to let you know that this issue is giving me a massive headache... 

@imcgames Please let me know your thoughts.

**Comment by Soukyuu** [comment]
Discord doesn't have a linux version, which makes me sad as I'm only using windows when I'm playing (also, a funny name for an app that is supposed to make collaborations easier... not seed discord :D)

Pull requests with 1-2 fixes are the ones easier to handle, imho. You don't have to review a lot before merging and the chance of conflict is less than humongous 100 line PRs.

I think the X marking issue was covered enough in #790 and #807, the rest is up to @imcgames 

On a general note, while many translators are a good thing to speed up the process, there should be only a few editors. This is mainly due to the fact every editor has their own style. Even with strict consistency rules in place, people will be able to tell the text was edited by several people.

The workflow we have in another translation project I'm part of is basically translate -> edit -> let other people proofread -> edit again if necessary, and it has been working very well.

My contributions so far have been minor spelling, formatting and inconsistency fixes, as I'm not a native English speaker, nor know any Korean. I do think my English is proficient enough for proofreading and posting suggestions on wording, though.

**Comment by Soukyuu** [comment]
I also forgot to add that if you plan to communicate via VoIP, you will have someone keep logs. Not everyone is in the same timezone, plus you don't want to have to answer the same questions repeatedly.

**Comment by Sunaries** [comment]
> I also forgot to add that if you plan to communicate via VoIP, you will have someone keep logs. Not everyone is in the same timezone, plus you don't want to have to answer the same questions repeatedly.

Discord is still in development, so there are features missing that other users might deem important. Right now, if you log on Discord and you missed a few hours of discussion, you'll have to scroll up and read all the unread messages. They are working on various upcoming features, including history. Linux version is in development :wink: 

> Pull requests with 1-2 fixes are the ones easier to handle, imho. You don't have to review a lot before merging and the chance of conflict is less than humongous 100 line PRs.

Sure they are easier, but will it make you a happy man when you have to review 300 pull requests consisting 1-2 fixes? There is a lot text in all the separate files that require attention. 1-2 fixes are contributions, but it would be really helpful if users could contribute more than that in **one** pull request.

**Comment by ensata** [comment]
An excellent report. This was actually something I wanted to see from @imcgames themselves, rather than someone else... so I have to say I'm shaking my head a little bit. Korean MMOs have a seriously poor reputation of bad translation and poor handling in the West, so I've been watching it carefully.

I have kind-of-quietly been creating the roots that's required to solve some of these issues over the previous month, based on my own experience with translation, and posted it publicly. It was meant to hint that something more was really required for the project, which only a few people have taken note of.

**For the wiki**, it actually requires more detail in order to understand and follow correctly, which was why I shared my personal setup and notes: [This is a general list](https://github.com/ensata/TreeOfSavior-en-research/blob/master/Keyword_notes.tsv), and [here are the map names.](https://github.com/ensata/TreeOfSavior-en-research/blob/master/mapnames.tsv)

**For translation**, contrary to what anyone believes about their English ability, a writing style guide is required, so [I wrote a really basic one.](https://github.com/ensata/TreeOfSavior-en-research/blob/master/Style_Guide.txt)

**For pull requests**, since very few contributors have shown a sign of understanding GitHub, I wrote [a list of do's and don'ts.](https://github.com/ensata/TreeOfSavior-en-research/blob/master/GitHub_Usage.txt)

There is also the final issue which I sent to imcgames in private, and I don't consider their hasty response to fix it to be enough - **the rights of the translators and editors, and proper licensing agreements.** I wanted to give imcgames some time to form a proper decision without a messy scramble, but they did it anyway. And the privacy of that email was thrown out the window. 

Unless someone wants me to elaborate on that part, I'll just say that I mentioned three exit-strategies that I have witnessed in the past, and unless something changes after I post this, imcgames has appeared to have chosen the most complicated and legally sensitive exit strategy.

**Comment by emailboxu** [comment]
I personally think there should be a debug client for translators so we can actually check translations in-game and use the RTT... It's way too hard to co-ordinate efforts on a text-only repository.

**Comment by vegax87** [comment]
In the README it's written: We will not merge your contributions in the Game until August 23rd.

**Comment by Requinn** [comment]
We are very aware. That is part of the reason this post was made, to take this time and do some organizing.

**Comment by Flevalt** [comment]
Closed my Issues.

**Comment by Xenobius2501** [comment]
I am currently working on probably the biggest list of Lihuanian-heavy terms  in #581 - namely, the sub-area section of Maps. This is going to take some time since I cannot fully commit to it during weekdays (gotta work sometimes), but it's getting there. 

As I already mentioned, it would be of great help if we could somehow get our hands on complete sub-area names, since Wiki only lists the first half, leaving it hard to guess the correct tense, case or number (all of these are tricky in Lithuanian). I have some screenshots from iCBT1, but comparing  the number of areas I managed to visit to total area number it's a drop in the ocean. 

As @emailboxu said, debug client would be extremely nice, but I don't think it's likely we'll get one. How about tools people use to access in-game resources (I definitely saw someone on forums post  3d models pulled from the game) - is it possible to butcher client files for map/item/quest data? 

P.S.: As far as time zones are concerned, I'm currently in a GMT+3 one (Vilnius, Lithuania). Usually I can find a bit of time during work to sneak a look at github/forums, but I can only access my home computer after 20:00 weekdays, plus whatever time I have during weekends.

**Comment by Soukyuu** [comment]
> Discord is still in development, so there are features missing that other users might deem important. Right now, if you log on Discord and you missed a few hours of discussion, you'll have to scroll up and read all the unread messages. They are working on various upcoming features, including history. Linux version is in development :wink:

What you describe is not VoIP (Voice over IP), but a chat(group) :wink:
I saw that a linux client is in development after I posted that, but thanks for pointing it out.

**Comment by laurencee** [comment]
@Soukyuu Does the web browser version of Discord not work on Linux? You can use VOIP & chat through the web browser client.

Discord has both historical chat channels + a VOIP server all in one.

**Comment by Soukyuu** [comment]
Ah, I need to work on expressing myself more clearly. I suggested keeping logs of the voice conversations, because they are not automatically logged like the text ones, but Sunaries said I can just scroll up and read up on the backlog. If we're going to mostly use the text chat, then there is no need to do anything, of course.

**Comment by imcgames** [comment]
We'll try to have things arranged and sorted out as much as possible in the next week or two. 
There are discussions going on internally and need some time to have it settled before we could decide on things for github so although there isn't so much I can say at this point, I'll try to answer as much as could. 

Pull requests 
- We'll close all pull requests made prior to 23rd. Please bear with us and don't send any until past 23rd.  
- For markings, we'll have a look into it first. Hopefully we can have that cleared by 23rd too. 

Discord
- You guys are awesome.  :+1: 

Issues
- For those that need to be closed, let us know on that issue by commenting on it and we'll have it closed as we see them.

Wiki
- As always, we are open to suggestions, if needed. 

Translation and Localization
- Yes, very much agreed. Let's stick to originals for now. Localization should come after the translation stage which we aren't past yet. 

Initially, we wanted to use the hiatus to also sort some things out for github.
And... although this wasn't really the process of sorting that we had in mind and things went forward earlier than we expected, I see that you guys are organizing things among yourselves and giving us feedback so I'd say it's a good thing that we still get to make the most out of this time.
We respect all your feedback and suggestions and thank you for showing such passion for Tree of Savior. 
Also, I apologize that the hiatus may be longer than first predicted in the previous issue.

**Comment by Soukyuu** [comment]
> For markings, we'll have a look into it first. Hopefully we can have that cleared by 23rd too.

The optimal way would be to have some sort of tag that the game doesn't parse (= is not visible), but will become visible once you open the .tsv file. At least that is what I've gotten from the replies to my initial proposal. Since you have full control over your game, I think you could do something about it.

**Comment by laurencee** [comment]
@imcgames Can probably close #504 #505 #569 #663 #780 #844

**Comment by laurencee** [comment]
More to close: #308 #321 #540 (this sort of information should be in your wiki and linked to from the readme, it shouldn't just be persisted as an issue)
#622 #705 (again this should be a wiki article and not an issue) 
#807 this is basically a duplicate of #476

**Comment by Rezken** [comment]
I agree with you @Sunaries.
I've also stopped sending Pull Requests for some since IMC didn't merge.
But I'll start again after the 23rd.

**Comment by terrapin47** [comment]
@Sunaries Suggest we rename this issue?  Maybe "Collaboration Instructions" or the like?

**Comment by ensata** [comment]
Aside from the link to the de facto Discord server, I wouldn't call these instructions. It's, well, a status report on what's currently wrong with the project. I'd still consider most of these unresolved, or needing considerably more information.

Depending on who's on the Discord server on Saturday morning (and whether I feel like it) I might go into more detail there... but no promises.
