### ISSUE TITLE
I have QUEST_JOBSTEP.tsv lines 758-1287.

### ISSUE THREAD

**Issue by Ragunaga** [Treeofsavior/EnglishTranslation#864]
EDIT: Yeah, me and a few other guys have basically the whole file done. It'd be great if you dropped into discord channel to see what still needs to be done, instead of submitting your own PR or working on your own to cut down on conflicts.

Just an FYI to those looking to working on it while PRs aren't being merged.

For those interested in viewing them;
(https://github.com/Ragunaga/EnglishTranslation/blob/patch-1/QUEST_JOBSTEP.tsv)
(https://github.com/Ragunaga/EnglishTranslation/tree/patch-2/QUEST_JOBSTEP.tsv)

**Comment by ttgmichael** [comment]
I think it'd be a better sidenote to say the QUEST_JOBSTEP file is NEARLY covered by @Ragunaga , Requinn, and zhouyu47 (Join the Discord server to see the progress xD). 

So everyone should try looking at the other files if they want to contribute after the 23rd (because you'll hit a lot of merge conflicts if you edit JOBSTEP. ^^

**Comment by Ragunaga** [comment]
Yep, as ttgmichael said, we basically got QUEST_JOBSTEP covered over here in discord. It would be great to check in over here before you do anything~

We think we can actually get the whole file done by the 23rd.

**Comment by ttgmichael** [comment]
Would you like to change the title to make it more fitting of the content? ^^
