### ISSUE TITLE
When to start translating?

### ISSUE THREAD

**Issue by WorksWellWithOthers** [Treeofsavior/EnglishTranslation#894]
Are we allowed to start translating now?

How many lines minimum should be included in one pull request?

**Comment by ttgmichael** [comment]
I believe so, as long as you have agreed with the CLA ;)

There's not really a minimum line requirement, but we'd prefer that people try and edit more lines per PR (like at least 10 ish). Otherwise, the queue line for PRs just get too big. lol.

It's probably more likely people want others to READ WHAT OTHERS HAVE DONE already before you try and make a smaller PR with the same edits. ^^

**Comment by WorksWellWithOthers** [comment]
Thank you.

#Note 
I accepted the CLA ;)
