### ISSUE TITLE
IMC, do you review PRs thoroughly?

### ISSUE THREAD

**Issue by Sunaries** [Treeofsavior/EnglishTranslation#915]
3 days ago, I submitted this PR: https://github.com/Treeofsavior/EnglishTranslation/pull/881/files. It covered a minority of updated skill descriptions. It was accepted. While mine has some minor grammatical mistakes that I need to iron out, I can't believe that many of my changes were overriden by this large PR: https://github.com/Treeofsavior/EnglishTranslation/pull/898. 

Since I won't return on my PC till tomorrow. But now, I spot some weird skill descriptions from https://github.com/Treeofsavior/EnglishTranslation/pull/898 that I have ironed out earlier in my PR, for instance:
- the description of Impaler;
- reverting Steed Charge to Stead Charge;
- reverting Frenzy to Flange;
- naming Critical Rate "critical strike rate". 

These are just a few examples.  

It is possible that some skills have been updated in Korea, but that does **NOT** mean we should incorporate the new description into the old files... This is the English version. IMC, you should do a better job at reviewing new PRs. 

If @imcgames didn't accept the PR and the author decided to split its work into parts, then I and others could have taken a peek at it. Now, this just causes extra work. Thanks... :disappointed:

**Comment by terrapin47** [comment]
This is certainly a problem.  I propose that we enact a system ( that is natural to pull requests ) where any new pull request is considered "in-review" and is not accepted until it is reviewed by someone in the community and accepted.

I was assuming that any PR with unresolved comments was not ready to be accepted, but this isn't the case.  It should be.  There are several PR's, including #898, that needed a lot more work/review until they were ready.

**Comment by ensata** [comment]
There's also been stuff that's clearly in the middle of review, but seemingly accepted regardless of its state – I'm pretty sure https://github.com/Treeofsavior/EnglishTranslation/pull/890 marks the fifth time that the same lines were done again, and this one was a major leap backwards.

The problem's not new, either. I've mostly just ignored it because it didn't seem to happen often. There was also another separate issue with https://github.com/Treeofsavior/EnglishTranslation/pull/898 that I hoped imc would've been more aware of by now... but I guess I was wrong.

**Comment by terrapin47** [comment]
Yes, I was doing several passes on #890 and #893, and my work was not complete, but they were just accepted.  The remaining issue with these is that they had good changes in them, but a lot of changes were just moving words around, or using synonyms when the original lines were completely fine.  I don't think we should be accepting line changes that don't actually need to be made, else each new proofreader will continually change lines just to add synonyms, and eventually a line can change meaning altogether due to a [telephone](https://en.wikipedia.org/wiki/Chinese_whispers) effect.

Also, I propose that we undo the merge of #898.  There are a lot of errors that were pointed out by @ttgmichael in a comment on that PR that were not fixed prior to merge, and a lot of potential errors since no one was able to review these changes fully.

@imcgames, managing these PRs and reviewing them is a tough job for one person.  I believe you should allow the community to set review standards and help with the process.

**Comment by imcgames** [comment]
For https://github.com/Treeofsavior/EnglishTranslation/pull/898 , I thought the comment made by @ttgmichael summed up the reviews from discord community and the stuff pointed out in that comment, along with others,  were checked before merging.
(that's why the PR wasn't merged as early as other PRs and only about a third of the changes in https://github.com/Treeofsavior/EnglishTranslation/pull/898 were actually merged)

Same goes for https://github.com/Treeofsavior/EnglishTranslation/pull/890 and https://github.com/Treeofsavior/EnglishTranslation/pull/893 where we assumed the update to the PRs made after the comments cleared the issues pointed out in that PR's comments. 

Hmm... Since it seems that assuming things kinda caused this issue, to prevent this, I think @zhouyu47 's suggestion to enact some marking system for PRs sounds good, if you guys also agree with it. 
If there's an open comment in the PR, we'll try not to merge them until there's some kind of 'good to merge' signal. What do you guys think?

**Comment by ghost** [comment]
I agree. There should be a 'good to merge' signal from the author of the pull request and from two (or more) other contributors. I agree I messed up in PR #890 and hoped to double-check everything in regards to what ensata pointed out once more before the merge happened.

**Comment by grillo-delmal** [comment]
The 'good to merge' from the author seems redundant since the "pull request" it's actually the authors way of saying 'good to merge'...

How about this:
- If there are no annotations, it needs just a "good to merge" comment from one contributor.
- If there are annotations, it needs a "resolved" comment from the author and two "good to merge" from contributors.

**Comment by vtange** [comment]
@Grillo-del-mal 
Sound's like a good system since it adds a layer of proofreading. I would then be wary of who counts as a "contributor". If we implemented your system right now any group of 3, regardless of how much they know of the game/done before could team up together to push requests through.

**Comment by grillo-delmal** [comment]
@vtange 
Well, but anyone can make an annotation if that happens, and its still better than what we have now :)

**Comment by terrapin47** [comment]
@senhart This could be managed by instantly leaving a comment on your pull request, stating that you want to have a review and will re-review it yourself before giving your 'good to merge' message.  Else, it would be assumed that you as the author were in favor of your own changes being merged.

@Grillo-del-mal I would agree with what you have proposed.  This should allow enough checking and discussion to properly resolve most problems.

@vtange I understand the worry, but in order to foster progress, I believe we should be more defensive rather than offensive with regulations regarding the whole process.  If it becomes a problem - that a group takes advantage of the rules and tries to push a pull request through - we should respond to it then.

**Comment by ensata** [comment]
Actually, a pull request doesn't necessarily mean that it's good to merge — there are a few ways you can exploit them and interpret them, based on what what a pull request does at its core: Its a request to merge two branches, but it _also highlights the diff in the process._

For example, I actually had no intention of having [this pull request](https://github.com/Treeofsavior/EnglishTranslation/pull/590) accepted at all. I knew that conflicts would be created, but it was the easiest way to highlight the exact problem at hand.

If you make a PR before you do anything at all, you can use that as a way to highlight what you plan to do (and then you could have people contributing on that fork first, before it cascades into the base branch, etc.) or if you submit the PR halfway through, it's a way of showing your work-in-progress code and ask for comment or help. I think there's even a function that blocks pull requests from being merged at all if 'WIP' is in the title, but that's not on GitHub.

**Comment by terrapin47** [comment]
@ensata This is true, and is another good way to do things.  As an author, if this is your intent, you can leave a comment on your own pull request stating that this is the case.  Although, typically with a proper pull request flow to an open source repository, the default is assumed to be that the author is proposing that these changes be made, and is okay with them.

So, to add to the original proposal, we could say this:
- The author should comment and state their purpose at the time they submit a pull request, unless they are confident in their changes.
- A contributor should proofread the changes, and if there is no other discussion, then they can give a 'good to merge' message, which will be sufficient.
- A contributor can leave a comment ( or more ) proposing a change to the pull request - the change should either be accepted by the author, or discussed.  The author and contributor should come to a consensus on the final state of the changes.  Then, a third contributor should proofread the  final changes, and give a 'good to merge' message.

**Comment by grillo-delmal** [comment]
@ensata 
Didn't knew that people used Pull Requests that way here. Normally when you use git, you work on your branch and you don't ask for a Pull Request until you are sure that it's ready to merge, but this comes from my experience as a programmer... 
@zhouyu47 provided a good way to manage this case by " instantly leaving a comment on your pull request, stating that you want to have a review and will re-review it yourself before giving your 'good to merge' message"... which is actually what you did on your example :)

**Comment by grillo-delmal** [comment]
@zhouyu47 didn't saw your comment, I say "good to merge" :+1:

**Comment by imcgames** [comment]
Alright, so if you want your PR to be reviewed, please indicate it when you send your pull requests. 
If there are no comments in the PR from anyone else for a day, we'll have it merged but if there are any comments pointing out for edits or errors, we'll wait for a 'good to merge' signal before we merge it. 
For PRs that are fairly simple, I don't think a 'good to merge' signal is really necessary so we'll try to have them merged in our discretion. 

Btw, we also need to set some time limit on how long we'd wait for a 'good to merge' or any additional comment if someone comments on the PR. 
Like if someone point out some error, but there is no comment/update/any action afterwards for 2 days or so, we'll either have the PR closed or changed from our side, depending on the contents of the PR. 

Also, to make things less complicated, if it isn't your intention to have the PR merged, then don't send them as a PR. If it's just to point out problems, then let's make use of the 'Issues' instead. :wink:

**Comment by laurencee** [comment]
@imcgames  That sounds like a good solution to me.

**This is just my opinion so if others disagree please let it be known.**
I believe that pull requests with more than 150 lines that aren't from the recognised main translator group should probably just be rejected and require the person to split their PR into smaller chunks so they can be reviewed properly.
There is not much point having the guidelines if a hard line isn't taken adhering to those rules.

In general even the main group should be committing smaller chunks that can be reviewed on the site so as to lead by example.

Large PRs are going to cause these sorts of issues more than any other PRs and it's really not that hard to break up PRs into multiple chunks...

It should become less and less common for larger PRs anyway as more of the files are properly translated, so this will mostly just be a short(ish) term problem to deal with.
