### ISSUE TITLE
QUEST_JOBSTEP: redundant lines?!

### ISSUE THREAD

**Issue by Soukyuu** [Treeofsavior/EnglishTranslation#933]
So it turns out that some untranslated lines around 2996 are actually (partially) the same as the ones around 745. The only difference is that the stories at 745 are more complete and use "" for dialogue, while the ones at 2996 are using [] and are incomplete (skipping lines).

While we could of course re-use the translations from earlier lines, the question is, why is the redundant text there in the first place? Maybe they should be removed altogether? 

Please shed some light on this, @imcgames

**Comment by imcgames** [comment]
Texts from the game are accumulated to the translation file, not refreshed. 
We can have unused lines removed but that'd result in the change of lines since there will be a lot of lines removed in the middle of the file.  (ex. 1,2,3,4,5,6... -> 1,2,5,8,9,10...)
I'm not sure if you remember but we did try removing unused lines few months ago but the result was kinda chaotic with the PRs so we actually had them back.  :cry: 

However, in line with this issue, we're actually trying to come up with some way to at least mark the lines that are no longer used rather than removing the line itself. It's something that is still under discussion with devs so we wanted to let you guys know after we finalize things but maybe we'd just share it with you ahead since this issue was brought up. :stuck_out_tongue_winking_eye: 
(but again, as all developments go, please note that it hasn't been finalized yet)

**Comment by Soukyuu** [comment]
Ah, I think that was before I joined. A pity, the PR block after the CBT was the perfect time to weed them out, and any new PRs would have to have been rebased on the clean version.

**Comment by Sunaries** [comment]
@imcgames There are many duplicate lines in SKILL as well, like the skill descriptions. Is it possible for you to mark or highlight which lines are referred to in the game. 
Because I've changed some skill descriptions, but I don't see it changed in the test server. That is because there is another duplicate line that does affect the description in the test server.

**Comment by Soukyuu** [comment]
I could imagine doing something like
- set a deadline for PRs after a beta
- stop accepting PRs
- weed out lines that aren't used anymore
- update the repo
- start accepting PRs again

Should allow to get rid off the unused lines and not run into issues with lines shifting.

**Comment by ttgmichael** [comment]
^ I'd approve of that idea. Or we can ix all unused lines so they are already "finalized".

**Comment by Soukyuu** [comment]
There is also the problem with lines (e.g. skill descriptions) being updated on the Korean side - we need some way to track this, so that we can update the translation as well.
